define HEADLESS_BOOT_SCENARIOS = #128;
define HEADLESS_SCHEDULER_SCENARIOS = #129;
define HEADLESS_OBJECT_SCENARIOS = #130;
define HEADLESS_RELATION_SCENARIOS = #131;
define HEADLESS_RULE_SCENARIOS = #132;
