name: Meadow CI

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    container: node:20-bookworm
    
    steps:
    - name: Checkout code
      uses: https://code.forgejo.org/actions/checkout@v4
    
    - name: Install dependencies
      run: |
        echo "@moor:registry=https://codeberg.org/api/packages/timbran/npm/" > .npmrc
        npm ci
    
    - name: Run lint
      run: npm run lint
    
    - name: Run TypeScript compilation
      run: npm run build
