object MAIL_HELP [
  import_export_id -> "mail_help"
]
  name: "Mail Commands Help Db"
  parent: GENERIC_HELP
  owner: HACKER
  readable: true

  property "@add-notify" (owner: HACKER, flags: "rc") = {
    "Usage:  @add-notify me to player",
    "    Sends mail to player saying that I want to be added to their mail notification property.",
    "Usage:  @add-notify player to me",
    "    Makes sure that player wants to be notified, if so, adds them to my .mail_notify property.",
    "",
    "In order for one person to be notified that another person has new mail, both the mail recipient and the notification recipient should agree that this is an OK transfer of information.  This verb facilitates that transaction."
  };
  property "@answer" (owner: HACKER, flags: "rc") = {
    "Syntax:  @answer [<message-number>] [sender] [all] [include] [noinclude] [followup]",
    "",
    "Synonym: @reply",
    "",
    "Prepares for you to compose a MOO email message to the players who either received or composed the indicated message from your collection.  The usual editor is invoked (see `help editors' for details).  The subject line for the new message will be initialized from that of the indicated message.  If you leave off the message number, the reply will be to your current message, if that exists.  In fact you may give a general message-sequence (see `help message-sequences') argument here, provided that it indicates only a single message (e.g., `@answer last:1')",
    "",
    "If there is a Reply-to: field in the message you are @answer'ing, its contents will be used to initialize the To: line of your reply.  Otherwise, a To: line is determined depending on whether you specified `sender', `all', or `followup' in the command line (or your .mail_options).",
    "  `sender'   replies to sender only",
    "  `all'      replies to sender and all original recipients",
    "  `followup' replies to first original recipient that is a non-player",
    "             (no effect if there are no non-player recipients).",
    "",
    "`include' includes the text of the original message in your reply, `noinclude' does not.  ",
    "",
    "`sender', `all', `followup', `include', and `noinclude' can all be abbreviated (e.g., `@answer i').",
    "",
    "Defaults are `sender' and `noinclude', but you can change this by setting your .mail-options (see `help mail-options').  "
  };
  property "@copymail" (owner: HACKER, flags: "rc") = {"*forward*", "@refile"};
  property "@forward" (owner: HACKER, flags: "rc") = {
    "Syntax:  @forward <msg> [on *<collection>] to <recipient> [<recipient>...]",
    "Syntax:  @resend  <msg> [on *<collection>] to <recipient> [<recipient>...]",
    "",
    "Both of these commands take the indicated message in your (or some other) message collection, and sends it on to the indicated recipients in some form.",
    "",
    "@forward sends an entirely new message whose body is the original message (both headers and body).",
    "@resend sends the original message, but with a header containing the lines",
    "",
    "  From:  original-sender",
    "  To:    original-recipients...",
    "  Resent-By: you",
    "  Resent-To: new-recipients...",
    "",
    "If you prefer to have yourself in the From: line of messages you @resend, set the mail option `resend_forw (see `help @mail-options').  In this case, the message will instead have a header containing the lines",
    "",
    "  From:  you",
    "  To:    new-recipients...",
    "  Original-From:  original-sender"
  };
  property "@keep-mail" (owner: HACKER, flags: "rc") = {
    "Syntax:  @keep-mail [<message-sequence>]",
    "         @keep-mail none",
    "",
    "Synonym: @keepmail",
    "",
    "As a space-saving measure, there is a task that runs periodically and from all player collections removes those messages that are",
    "  (1) marked as read (i.e., dated before the last-read-date), ",
    "  (2) older than a certain expire time, and",
    "  (3) not specifically marked as \"kept\".",
    "",
    "\"kept\" messages will show up in your @mail listing with an `=' to the right of the message number.",
    "",
    "The first form of the @keep-mail command marks the indicated messages as kept.  The message-sequence argument is as with other mail commands (see `help message-sequences').  @keep-mail without any arguments marks your current message as kept.",
    "",
    "The second form of the command is used to remove all such marks from your mail collection.",
    "",
    "    @mail kept:",
    "",
    "will produce a list of all messages marked as kept (see `help message-sequences').",
    "",
    "You can use @mail-option expire (see `help @mail-option') to change your expire time.",
    "",
    "Kept mail remains in your mailbox until you remove it."
  };
  property "@keepmail" (owner: HACKER, flags: "rc") = {"*forward*", "@keep-mail"};
  property "@mail" (owner: HACKER, flags: "r") = {
    "Syntax:  @mail",
    "         @mail new            (to see recent messages)",
    "         @mail 1-$            (to see *all* messages)",
    "",
    "Shows a table of contents for your MOO email message collection.  You are notified when you connect to the MOO if there are any such messages.  A little arrow indicates the mail system's notion of your 'current message'.  ",
    "The first form lists all of your messages or the last 15 if you have more than that many; the second form lists only those messages after your `current message'.  The third form shows your entire collection.",
    "",
    "If you have a large number of mail messages, you can give arguments so that @mail only lists the messages you're interested in.  You can also list messages residing on mail recipients which are public or for which you have read access.",
    "The general format is",
    "",
    "         @mail <message-sequence> [on *<recipient>]",
    "",
    "<recipient> must name some child of $mail_recipient (e.g., a mailing list);",
    "<message-sequence> can be a sequence of message numbers; you can also scan the recipient for articles that fit a given description, as specified in `help message-sequences'.",
    "",
    "Note that if you view mail on some other recipient and have \"sticky\" in your .mail_options (see `help mail-options'), all further mail commands (e.g., @read, @next, @rmm,...) will apply to that recipient.  In this case use `@mail on me' to go back to looking at your own mail."
  };
  property "@mail-all-new-mail" (owner: HACKER, flags: "rc") = {"*forward*", "@nn"};
  property "@mail-options" (owner: HACKER, flags: "rc") = {
    "Syntax:  @mail-option",
    "         @mail-option <option>",
    "",
    "Synonym:  @mailoption",
    "",
    "The first form displays all of your mail options",
    "The second displays just that one option, which may be either `@mail', `replyto', or one of the flags listed below.  The mail options control various annoying details of your mail reading and mail editing commands.",
    "",
    "The remaining forms of this command are for setting your mail options:",
    "",
    "         @mail-option +<flag>",
    "         @mail-option -<flag>",
    "         @mail-option !<flag>           (equivalent to -<flag>)",
    "",
    "These respectively set and reset the specified flag",
    "",
    " -include          @replys start out with a blank message body",
    " +include          @replys start with original message included",
    " -all              @replys go to sender only",
    " +all              @replys go to sender and all original recipients",
    " -followup         @replys go as directed by `all' flag",
    " +followup         @replys go to first nonplayer recipient if any",
    "                    (if there are no non-player recipients, use `all' flag).",
    " -nosubject        @send forces you to provide a Subject: line",
    " +nosubject        allow entering the mail editor without giving a subject line",
    " -expert           novice mail user (various annoying messages will be printed)",
    " +expert           expert mail user (suppress printing of annoying messages)",
    " -enter            start each mail editing session in the usual command mode.",
    " +enter            start each mail editing session with an implicit `enter'",
    "                    command",
    " -sticky           each mail command applies by default to one's own collection",
    " +sticky           each mail command applies by default to the same message ",
    "                    collection that the previous successful command did",
    " -resend_forw      @resend puts player in Resent-By: header",
    " +resend_forw      @resend puts player in From: header (like @forward)",
    " -no_dupcc         send a personal copy even if already subscribed to a ",
    "                    mailing list on the to: line",
    " +no_dupcc         don't send personal copies of mail also sent to lists",
    "                    you are subscribed to",
    " -no_unsend        People may @unsend unread messages they send to you",
    " +no_unsend        No one may @unsend messages they sent to you",
    "",
    "For \"sticky\", `mail command' is one of @mail, @read, @prev, @next, @answer.",
    "All flags default to the `-' settings.  ",
    "",
    "Mail output is not paginated or wrapped; configure your client for long output.",
    "",
    "         @mail-option  @mail [is] <message-sequence>",
    "",
    "The \"@mail\" option determines what message-sequence the @mail command uses by ",
    "default.  Initially, this is \"last:15\", but other reasonable choices include",
    "\"new\" and \"1-last\"",
    "",
    "         @mail-option  replyto [is] <recipient> [<recipient>...]",
    "         @mail-option -replyto",
    "",
    "The first form specifies that a Reply-To: field is to be placed in all messages constructed by @send or @answer.  Note this can still be changed before sending via the mail room's reply-to command.  ",
    "The second form resets this option so that no Reply-to: is initially inserted.",
    "",
    "        @mail-option rn_order=<order>",
    "",
    "controls the order in which folders listed by @rn and @subscribed will appear.  <order> can be one of",
    "",
    " read    folders are sorted by last read date. (default)",
    " send    folders are sorted by last send date.",
    " fixed   folders are not sorted",
    "",
    "To control expiration of messages (see `help @keep-mail') we have",
    "",
    "        @mail-option expire [is] <time-interval>",
    "        @mail-option expire=<time-interval>",
    "",
    "<time-interval> can either be a number of seconds or something with units in it, e.g.,",
    "",
    "        @mail-option expire 13 days",
    "        @mail-option expire 1 year 39 days",
    "",
    "A negative number or",
    "",
    "        @mail-option +expire",
    "",
    "disables message expiration entirely",
    "",
    "        @mail-option -expire",
    "",
    "sets your message expiration time to the current default.",
    "",
    "        @mail-option @unsend=<message sequence>",
    "",
    "sets the default message sequence that the @unsend command will operate upon.  The default is \"last:1\"."
  };
  property "@mailoptions" (owner: HACKER, flags: "r") = {"*forward*", "@mail-options"};
  property "@next" (owner: HACKER, flags: "r") = {
    "Syntax:  @next [<number>] [on <collection>]",
    "",
    "Print the `next' message in a given email collection (defaults to your own).  The mail system's notion of your 'current message' for that collection is incremented.  Thus, e.g., one can read all of one's new messages one-by-one simply by typing '@next' repeatedly.  If <number> is supplied, prints and advances that many messages."
  };
  property "@nn" (owner: HACKER, flags: "rc") = {
    "Alternative mail reading commands.",
    "",
    "Syntax:  @nn",
    "",
    "This command finds a folder containing an unread message, displays the first such, and updates your last-read-time for that folder.  Your personal mail and all @subscribed folders are checked.",
    "",
    "Syntax:  @mail-all-new-mail",
    "",
    "Displays headers of all unread messages on all of your folders (i.e., your personal folder and all @subscribed folders).",
    "",
    "Syntax:  @read-all-new-mail",
    "",
    "Displays all unread messages on all of your folders (i.e., your personal folder and all @subscribed folders).  This command ends with a prompt, \"Did you get all of that? [Enter `yes' or `no'].\"  Answering \"yes\" causes all of your last-read times to be updated.  You will probably want to check for <<<n lines flushed>>> indications before you answer this question.",
    "",
    "@read-all-new-mail (with a \"yes\" answer at the end) is equivalent to doing a large number of @nn's."
  };
  property "@peek" (owner: HACKER, flags: "rc") = {"*forward*", "@read"};
  property "@prev" (owner: HACKER, flags: "rc") = {
    "Syntax:  @prev [<number>] [on <collection>]",
    "",
    "Print the 'previous' message in a given email collection (defaults to your own).  The mail system's notion of your 'current message' for that collection is decremented.  Thus, e.g., one can review all of one's previous messages one-by-one simply by typing '@prev' repeatedly.  If <number> is supplied, print (and decrement current message by) that many messages."
  };
  property "@qreply" (owner: HACKER, flags: "rc") = {"*forward*", "@quickreply"};
  property "@qsend" (owner: HACKER, flags: "rc") = {"*forward*", "@quicksend"};
  property "@quickreply" (owner: HACKER, flags: "rc") = {
    "Syntax:   @quickreply  <msg> [on *<recipient>] [<flags>...]",
    "          @quickreply  <msg> [<flags>...] [on *<recipient>] ",
    "",
    "Synonym:  @qreply",
    "",
    "The @quickreply command allows you to do a short reply to a mail message without heading for the mail room.  As with @reply, the subject line on the reply message is taken from the original.  <flags> are as with @reply, except that `include' is not recognized --- if you're going to include the original message, you *have* to trim it down, and that requires the editor."
  };
  property "@quicksend" (owner: HACKER, flags: "rc") = {
    "Syntax:   @quicksend <player> [subj=\"<text>\"] <one-line-message>...",
    "          @quicksend <player> [subj=\"<text>\"]",
    "",
    "Synonym:  @qsend",
    "",
    "The @quicksend command allows you to send a short mail message without heading for the mail room.  With the second form of the command you will be prompted for the body of the message (and a subject line unless your `nosubject' mailoption is set (see `help @mail-option') or you already gave a subject line)."
  };
  property "@read" (owner: HACKER, flags: "rc") = {
    "Syntax:  @read <message-number>",
    "         @read",
    "         @peek ...",
    "",
    "Prints the contents of the indiciated messages from your MOO email collection.  You get the message numbers for use here by typing the '@mail' command, which prints a table of contents for your entire MOO email collection.  If no arguments are given to @read, then the 'current message' in your collection is printed.  In any case, the 'current message' after @read finishes is the last one printed.",
    "",
    "The most general form of the @read command is",
    "",
    "         @read <message-sequence> [on *<collection>]  ",
    "",
    "where <message-sequence> is as described in `help message-sequences'.",
    "As with the @mail command you may @read messages on any publically readable collection (child of $mail_recipient).",
    "",
    "The @peek command is a variant of @read that works no differently except that it refrains from setting your `current message'.  This is useful, for example, if you want to see some particular message on a collection without losing track of where you are in it."
  };
  property "@read-all-new-mail" (owner: HACKER, flags: "rc") = {"*forward*", "@nn"};
  property "@refile" (owner: HACKER, flags: "rc") = {
    "Syntax:  @refile <message-seq> [on mail-recipient] to mail-recipient",
    "         @copymail <message-seq> [on mail-recipient] to mail-recipient",
    "",
    "Moves a message sequence directly from one mail recipient (defaulting as per the sticky @mail-option) to another, without adding headers or reordering.",
    "",
    "NOTE:  The recipient of @refiled messages may well have its mail out of order.  This can confuse a variety of features of the mail system, which expects its messages to always be in chronological order.  Care should be exercised with @refile/@copymail."
  };
  property "@refusal-reporting" (owner: HACKER, flags: "rc") = {
    "[See help @refuse for a discussion of the refusal facility]",
    "",
    "    @refusals",
    "    @refusals for <player>",
    "",
    "List the players and actions you are refusing, or the players and actions that another player is refusing. For example, you can see if",
    "Stupid_Jerk is refusing your mail too: '@refusals for Stupid_Jerk'.",
    "",
    "Normally refusal works without your awareness. You don't even notice when Stupid_Jerk attempts to send you mail. If you would rather be",
    "notified when it happens (so you can thumb your nose), then do",
    "",
    "    @refusal-reporting on",
    "",
    "Actually, all you need to type is '@refusal-r on'. You will see a message like 'Mail from Stupid_Jerk (#34567) refused.' as soon as",
    "Stupid_Jerk types 'send' in the mail editor.",
    "",
    "Refusal reporting only works for some actions. It works for page, whisper, and mail, but not for move, join or accept. Sorry.",
    "",
    "You will only be notified if you are connected when the refusal happens. If you are not connected when Stupid_Jerk tries to send you mail,",
    "you won't know about it, no matter whether refusal reporting is on or off.",
    "",
    "You can turn off refusal reporting with '@refusal-r off'. You can check whether it is on or off with '@refusal-r'. Here's the list:",
    "",
    "    @refusal-reporting on     - turn on refusal reporting",
    "    @refusal-reporting off    - turn off refusal reporting",
    "    @refusal-reporting        - see whether it is on or off"
  };
  property "@refusals" (owner: HACKER, flags: "rc") = {"*forward*", "@refusal-reporting"};
  property "@refuse" (owner: HACKER, flags: "rc") = {
    "",
    "The refusal facility allows you to ignore specific actions by players. You can ignore all mail that Stupid_Jerk (#34567) sends you, for",
    "example, or you can ignore all whispers and pages, no matter who they are from.",
    "",
    "There are three basic refusal commands. They are explained below.",
    "",
    "    @refuse <action> from <player>",
    "    @unrefuse <action> from <player>",
    "    @refusals",
    "",
    "The actions you can refuse are page, whisper, mail, move, join, and accept. These are explained in a table farther down.",
    "",
    "For example, '@refuse mail from Stupid_Jerk'. Any future mail that Stupid_Jerk sends you will be dropped on the floor, and Stupid_Jerk will",
    "be told that you refused to receive it. The refusal stays active for a week; after the week is over, Stupid_Jerk's mail will again get",
    "through. (If you want the refusal to last a longer or shorter time, keep on reading.)",
    "",
    "You can refuse more than one action at a time. '@refuse page whisper from Stupid_Jerk' refuses both pages and whispers.",
    "",
    "You can also refuse actions from everybody.",
    "",
    "    @refuse <actions>",
    "",
    "For example, '@refuse page' refuses every page. These refusals are listed as refusals of 'everybody' when you use the @refusals command,",
    "below.",
    "",
    "See `help @unrefuse' and `help @refusal-reporting' for information on undoing refusals and finding out what you're refusing.",
    "",
    " - the actions",
    "",
    "The actions everybody can refuse are page, whisper, mail, move, and join.",
    "refuse other things as well, depending on your player class.",
    "",
    " refuse this      to prevent somebody from doing this",
    " -----------      -----------------------------------",
    "    page        - tell you a message with the 'page' command",
    "    whisper     - tell you a message with the 'whisper' or 'murmur' command",
    "    mail        - send you a MOOmail message via @send",
    "    move        - teleport you",
    "    join        - enter the same room as you (only works in a some rooms)",
    "    accept      - hand you an object (or teleport it to you)",
    "    flames      - posts are suppressed on mail lists",
    "    politics    - set yourself `apolitical' [see `help apolitical']",
    "    all         - all of the above",
    "",
    "Refusing move is a little tricky. The player will not be able to teleport you, but you will not be able to pass through any special exits",
    "that the player may have programmed either. Refusing move means refusing *all* movement, including movement through programmed exits.",
    "Fortunately most exits are plain exits, and you will always be able to pass through them. Only specially programmed exits by the player you",
    "are refusing move from are barred to you.",
    "",
    "Refusing join only works in special rooms that support it.",
    "",
    " - time limits",
    "",
    "Refusals expire after a certain amount of time has gone by. Unless you say otherwise, they expire after a week. You can add '... for",
    "<time>' to the end of a @refuse command:",
    "",
    "    @refuse <action> from <player> for <time>",
    "    @refuse <action> for <time>",
    "",
    "For example, '@refuse join from Stupid_Jerk for 3 days'.",
    "",
    "The <time> is always a number followed by a unit, like '10 weeks' or '45 seconds'. The possible units are second, minute, hour, day, week,",
    "and month."
  };
  property "@renumber" (owner: HACKER, flags: "rc") = {
    "Syntax:  @renumber [<collection>]",
    "",
    "Renumbers the messages in your collection to go from 1 to however many you have at the moment.  The optional argument allows you to renumber the messages stored in some other collection (@renumber, like @rmmail, requires write access).",
    "",
    "Note that if you have zombie messages from a previous @rmmail command (see `help zombie-messages'), these will be expunged."
  };
  property "@reply" (owner: HACKER, flags: "rc") = {"*forward*", "@answer"};
  property "@resend" (owner: HACKER, flags: "rc") = {"*forward*", "@forward"};
  property "@rmmail" (owner: HACKER, flags: "rc") = {
    "Syntax:  @rmmail [<message-sequence>] [from *<recipient>]",
    "",
    "Deletes the indicated messages from your MOO email collection.",
    "By default, your current message is deleted.",
    "See `help message-sequence' for the full list of possible arguments.",
    "You get the message numbers for use here by typing the '@mail' command.",
    "",
    "There is no confirmation for this action, so be careful.  While it is true that @unrmmail will be able to bring back the messages deleted by the last @rmm, any messages deleted before then are really gone, i.e., irrecoverable.  See `help @unrmmail' for more information.",
    "",
    "This command may be used on other mail recipients (children of $mail_recipient), but only ones to which you have write access (you either have to own it or be on good terms with whoever does...).",
    "",
    "You can try to delete messages that you accidentally sent to a person with the command @unsend (see `help @unsend').  Note there are restrictions on the operation, so it often will not work."
  };
  property "@rn" (owner: HACKER, flags: "rc") = {
    "Syntax:  @rn",
    "",
    "For each collection of mail messages that you read other from your own, a last-read-time is kept.  This command tells you which collections (out of all those you have ever read) have recently had messages added to them, i.e., more recently than when you last did a @read, @prev, @next, or @skip on that collection.",
    "",
    "Etymologists' note:  If you thought @rn had anything to do with the popular UNIX newsreading program `rn', it's just your imagination."
  };
  property "@send" (owner: HACKER, flags: "rc") = {
    "Syntax:  @send <recipient> [<recipient> ...]  [subj[ect]=\"<subject>\"]",
    "",
    "Prepares for you to compose a MOO email message to the recipients named on the command line.  A recipient can be specified by giving a player name or object-id, or a '*' followed by the name or object-id of some non-player mail recipient (e.g., a mailing list or a mail folder) -- a list of such non-player recipients is available from within the mailroom with the 'showlists' command.",
    "",
    "The usual editor is invoked.   ",
    "You will be prompted for a subject line if you did not specify one in the @send command (see `help mail_options' for how to avoid this).",
    "Use `say' (\") to insert lines in the body of your message.  ",
    "See `help editors' for details.",
    "",
    "Giving this command without arguments resumes editing the previous unsent draft message if one exists."
  };
  property "@skip" (owner: HACKER, flags: "rc") = {
    "Syntax:  @skip [<collection>...]",
    "         @unsubscribe [<collection>...]",
    "",
    "For each collection of mail messages that you read other from your own, a current message and a last-read-time is kept.  Normally, if you neglect to actually @read any messages on a collection other from your own, @rn (or :check_mail_lists) will continue to remind you that they are there.",
    "",
    "The @skip command indicates that you're not interested in reading the rest of the messages that currently exist in that given collection.  ",
    "",
    "The @unsubscribe command flushes the current-message/last-read-time information completely, indicating that you are not only uninterested in the rest of the messages on that collection, but also likewise uninterested in anything else that may appear on that collection later on.  @unsubscribe also removes you from the collection's .mail_notify list."
  };
  property "@spurn" (owner: #2, flags: "r") = {"*verbdoc*", "$mail_recipient_class", "@spurn"};
  property "@spurned" (owner: #2, flags: "r") = {"*verbdoc*", "$mail_recipient_class", "@spurned"};
  property "@subscribe" (owner: HACKER, flags: "rc") = {
    "Syntax:  @subscribe *<collection> [with|without notification] [before|after *<collection>]",
    "         @subscribe",
    "         @subscribe-quick",
    "",
    "The second and third form of the command gives a list of all mail collections that are readable by you. The third form omits the mail collection description.",
    "",
    "The first form of this command sets up a current message and a last-read-time for the given mail collection so that when you next log in or issue the @rn command, you will be informed about new mail that has appeared there.  Note that this happens automatically whenever you @read messages on a given collection, so if this much is all you care about, you don't need to use this command; just do, e.g.,",
    "         @read last on *<collection>",
    "",
    "Specifying \"with notification\" causes you to be added to the immediate-notification list (.mail_notify) for that collection, i.e., whenever new mail arrives there, you will be notified immediately.  Specifying \"without notification\" causes you to be removed from the collection's .mail_notify.",
    "",
    "Specifying \"before *<other-collection>\" causes <collection> to be placed immediately before *<collection> in your @rn listing (which see) and likewise for the \"after\" clause.  By default, new collections are placed at the end of your list.  The before/after specification is only useful if you have @mail-option rn_order=fixed set (see `help @mail-options').",
    "",
    "@subscribing to a collection for which you already have a current-message/last-read-time has no effect other from possibly changing that collection's .mail_notify and/or reordering your collections for @rn.",
    "",
    "You can only @subscribe to collections that are readable by you.",
    "",
    "Note that this is entirely different from the Mail Room `subscribe' command",
    "which actually adds you to the .mail_forward list for a given collection/",
    "mailing-list, so that mail sent to the list actually shows up in your own",
    "mail collection.",
    "We're probably going to phase out the Mail Room `subscribe' command..."
  };
  property "@subscribed" (owner: HACKER, flags: "rc") = {
    "Syntax: @subscribed",
    "",
    "Like @rn, but shows you ALL mailing lists to which you are subscribed, even those which have no new messages."
  };
  property "@unrefuse" (owner: HACKER, flags: "rc") = {
    "Syntax:",
    "    @unrefuse <actions> from <player>",
    "",
    "If Stupid_Jerk reforms, you can change your mind. '@unrefuse mail from Stupid_Jerk' will remove the refusal.",
    "",
    "'@unrefuse' can also be called '@allow', for those who prefer English over clarity.",
    "",
    "    @unrefuse <actions>",
    "",
    "If you don't mention a player, you remove only refusals that apply to everybody. '@unrefuse page' turns off any '@refuse page' command you",
    "gave before, but does not affect refusals of specific players. You will still be refusing pages from Stupid_Jerk, if you were before.",
    "",
    "    @unrefuse everything",
    "",
    " If you '@unrefuse everything', all your refusals are removed. This command asks if you are sure before erasing them all."
  };
  property "@unrmmail" (owner: HACKER, flags: "rc") = {
    "Syntax:  @unrmmail [list|expunge] [on *<collection>]",
    "",
    "When you do @rmmail on a particular message collection, the messages removed don't go away immediately, but are rather saved elsewhere.  These \"zombie\" messages can be brought back or examined using the @UNrmmail command.",
    "",
    "Without `list' or `expunge', @unrmm restores the zombie messages, thus undoing the effect of the most recent @rmmail command.  Only the most recent @rmmail can be undone in this way; messages deleted by any previous @rmmail commands on this same collection are lost and gone forever.",
    "",
    "The `list' option merely lists the headers of the zombie messages without actually restoring them.",
    "",
    "The `expunge' option banishes the zombie messages forever.",
    "",
    "Note that the message numbers used by zombie messages are held in reserve against the possibility that you might @unrmm them some day; with such messages around, new messages received will be given higher numbers than you might have expected.  @renumber does an implicit @unrmm expunge.",
    "",
    "`@unrmmail' and `@unrmmail expunge' on collections other than your own are only allowed when you have write access.  Likewise, `@unrmmail list' on other collections is only possible when they are readable by you."
  };
  property "@unsend" (owner: HACKER, flags: "rc") = {
    "The @unsend command was created by ballot on LambdaMOO, *B:Unsend (#77081).",
    "",
    "Syntax: @unsend [message-sequence] from <user>",
    "",
    "A message cannot be unsent to a player if e has read the message, it has been forwarded to eir e-mail address, or e has set an option to prevent messages being unsent to em.  A message cannot be unsent to a group of players unless it can be unsent to each player in the group.",
    "",
    "The unsender may not view a list of unread messages on a player.  E may only select the message(s) to be unsent by filters such as \"subject:<subject>\" or \"since:today\".",
    "",
    "In order to protect privacy, if any of the restrictions above, such as one of the users having already read the message, are not met, the error message will be quite generic and not tell you exactly what went wrong, but simply that messages could not be unsent.",
    "",
    "The following mail options are available:",
    "",
    "@mail-option +no_unsend      No one may @unsend messages they sent to you",
    "@mail-option -no_unsend      People may @unsend unread messages they send to you",
    "@mail-option @unsend=<message sequence>",
    "",
    "sets the default message sequence that the @unsend command will operate upon.  The default is \"last:1\"."
  };
  property "@unsubscribe" (owner: HACKER, flags: "rc") = {"*forward*", "@skip"};
  property mail (owner: HACKER, flags: "rc") = {
    "The MOO email system allows you to send and receive messages to and from other players.  It provides commands to view and manage your own collection of saved messages and, in addition, to browse through other collections that may be available (e.g.,archives of public mailing lists).  Help is available on the following commands:",
    "",
    "@mail     -- seeing a table of contents for a collection of email messages",
    "@read     -- reading individual messages ",
    "@next     -- reading the 'next'     message",
    "@prev     -- reading the 'previous' message",
    "",
    "@send     -- composing and sending a message to other players",
    "@answer   -- replying to one of the messages in a collection",
    "@forward  -- resending one of the messages in a collection somewhere else",
    "",
    "@rmmail   -- discarding some subset of a collection",
    "@unrmmail -- undoing the most recent @rmm on a collection",
    "@unsend   -- try to remove a message you accidentally sent",
    "@renumber -- renumbering the messages in a collection",
    "@keep-mail - marking messages in a collection as exempt from expiration",
    "",
    "@mail-option -- describes and sets various customization flags",
    "",
    "help mail-forwarding",
    " -- describes mail forwarding",
    "help message-sequences",
    " -- describes message-sequences arguments to @mail, @read, @rmm, and @answer.",
    "",
    "For viewing collections other from your own, the following commands are useful:",
    "",
    "@rn          -- list those collections that have new messages on them",
    "@subscribe   -- indicate that you want @rn to report on a given collection",
    "                  and add yourself to its .mail_notify list",
    "@skip        -- ignore any remaining new messages in a given collection",
    "@unsubscribe -- ignore a given collection entirely from now on",
    "                  and remove yourself from its .mail_notify list",
    "@unsubscribed-- show the mailing lists that you aren't subscribed to.",
    "@subscribed  -- like @rn, but shows all lists that you are subscribed to",
    "                even if they have no new activity"
  };
  property "mail-forwarding" (owner: HACKER, flags: "rc") = {
    "There are 3 personal properties that you can use to customize how your mail is composed and forwarded",
    "",
    ".mail_forward ",
    " -- list of objects that will receive any mail that gets sent to you.",
    "    Objects on this list should either be players or descendants of ",
    "    $mail_recipient.",
    "    If this list is nonempty, you will not receive any mail yourself unless",
    "    you are on it.  E.g., if Rog is #4292 and ur-Rog is #6349",
    "",
    "  #6349.mail_forward={}            -- usual case; ur-Rog gets his own mail.",
    "  #6349.mail_forward={#4292}       -- Rog gets ur-Rog's mail instead.",
    "  #6349.mail_forward={#6349,#4292} -- ur-Rog gets mail and Rog gets a copy.",
    "  #6349.mail_forward={#-1}         -- ur-Rog's mail disappears without a trace.",
    "",
    ".mail_notify",
    " -- list of objects to be notified whenever mail is sent to you.",
    "    This list may include anything that has a :notify_mail() verb.",
    "    Notification will take place regardless of whether or how your mail",
    "    is forwarded.  ",
    "",
    "Thus, in the previous example",
    "",
    "  #4292.mail_notify={#6349} --- means that ur-Rog will be told",
    "                                whenever Rog is sent new mail.",
    "",
    ".mail_options",
    " -- this controls lots of miscellaneous things.  Use the @mail-option command",
    "    to view and set these options (see `help @mail-option')",
    "",
    "See `help mail-resolve' for more detail on how mail forwarding and mail notification work.  See `help MR-subscribing' for information on how to change .mail_forward and .mail_notify on $mail_recipient children, where they are !c properties."
  };
  property "mail-index" (owner: HACKER, flags: "rc") = {"*index*", "Mail System Help Topics"};
  property "message-sequences" (owner: HACKER, flags: "r") = {
    "Certain mail commands, including @mail, @read, and @rmmail, allow a <message-sequence> argument that indicates to which messages in one's collection the command is to apply.  Any combination of the following may appear as a <message-sequence> argument to any of the various mail commands (@mail, @read, @answer, @rmm).",
    "",
    "  17        message number 17 if there is one (and likewise for other integers)",
    "  17..23    all messages numbered between 17 and 23 (inclusive), if any.",
    "  cur       the current message",
    "  prev      the message before",
    "  next      the message after",
    "  prev17    the 17 messages prior to the current message",
    "  next17    the 17 messages after the current message",
    "  first     the first message if any",
    "  last      the final message if any (`$' is a synonym for `last')",
    "  new       unread messages if any",
    "",
    "You may use as many of these at once as sanity permits, e.g.,",
    "",
    "  @mail cur 1..5 last",
    "",
    "which will display the header for your current message, your messages in the range 1..5, and your last message.  Though some of these ranges may overlap, the header for any given message is only shown once in any event.",
    "",
    "In addition, there are other message-sequence arguments that act as filters on whatever precedes them. ",
    "",
    " before:<date>               messages strictly before the given date",
    " after:<date>                messages strictly after the given date",
    " since:<date>                messages on or after the given date",
    " until:<date>                messages on or before the given date",
    " from:<player>[|<player...]  messages from the given player(s)",
    " to:<recip>[|<recip>...]     messages to the given recipient(s)",
    " %from:<string>              messages with <string> in the From: line",
    " %to:<string>                messages with <string> in the To: line",
    " subject:<string>            messages with <string> in the subject",
    " body:<string>               messages with <string> in the body (SLOW!!!)",
    " first:<number>              the first <number> messages",
    " last:<number>               the last <number> messages",
    " kept:                       messages marked as kept (see `help @keep-mail')",
    " unkept:                     messages not marked as kept",
    "",
    "<date>  is either a weekday, \"today\", \"yesterday\", or",
    "        a dd-Month, dd-Month-yy or dd-Month-yyyy date",
    "<recip> is either <player> or *<$mail_recipient kid>",
    "",
    "Examples:",
    "",
    "  @read from:G7|Gemba              read all messages from G7 or Gemba",
    "  @rmm to:yduJ|*Core               remove messages that are to yduJ or to *Core",
    "  @mail since:1-Jan before:1-Feb   show messages dated in January",
    "  @mail since:Tues                 show messages dated on or after Tuesday",
    "  @rmm subject:manners             remove msgs with `manners' in the subject:",
    "  @mail subject:\"stupid idiots\"    (search string contains a space => need \"'s)",
    "  @rmm to:yduJ to:*Core            remove messages that are to yduJ and *Core",
    "  @mail from:Haakon last:5         show the last 5 messages from Haakon",
    "  @mail %from:guest                show mail from players with \"guest\" in",
    "                                   their names",
    "  @mail last:10 body:fribble       show those of the last 10 messages having",
    "                                   `fribble' in the body (one should always try",
    "                                   to narrow body searches in this way)."
  };
  property "refusal-programming" (owner: HACKER, flags: "rc") = {
    "",
    "  -- -- --  refusal programming",
    "",
    "This entry explains how to program new kinds of refusal for the refusal mechanism. This information is only useful for programmers. For basic information about the refusal mechanism, read the 'refusal' entry.",
    "",
    " - making a new refusable action",
    "",
    "Making a refusable action has several steps. You have to (1) override the verb that lists your refusable actions, (2) write a verb to handle any special cases in determining when an action should be refused, and (3) write the code that does the actual acceptance or refusal of the action.",
    "",
    "You can put new refusable actions on yourself, or on a player class. If you put them on yourself, then you are the only one who can use them. If you put them on a player class, then everyone who belongs to that class can use them.",
    "",
    "I'll walk you through the example of making a refusable action 'smirk'. If you '@refuse smirk from Munchkin' then anything Munchkin tells you with the word 'smirk' in it will be refused. Since this is useless, I'll assume that you're defining it on yourself, instead of on a player class.",
    "",
    "(1) You have to make 'smirk' a refusable action. You do that by overriding your :refusable_actions verb. :Refusable_actions is a verb which returns the actions that you know how to refuse. It is a verb instead of a property so that players can add refusable actions at all levels of the player class hierarchy without interfering with each other.",
    "",
    "    @verb me:refusable_actions this none this",
    "    @program me:refusable_actions",
    "      return {@pass(@args), \"smirk\"};",
    "    .",
    "",
    "'@pass (@args)' means 'include the actions that my parent knows how to refuse, because I know how to refuse them too.'",
    "",
    "(2) The refusal mechanism provides for special cases in deciding whether an action should be refused. None of the refusals defined on the default player class actually make use of this special case, and you probably won't have to use it either. But you still have to write a verb to deal with it.",
    "",
    "The verb should be named :refuses_action_<action>, where <action> is the action that the verb is for. In this case, it should be :refuses_action_smirk. The verb takes some arguments and returns whether the action should be refused. The details of this will someday be explained in the next section, 'fancy refusable actions', but in all simple cases the verb should simply return 1.",
    "",
    "    @verb me:refuses_action_smirk this none this",
    "    @program me:refuses_action_smirk",
    "      return 1;",
    "    .",
    "",
    "(3) Finally you must implement the refusal itself. The code that performs the action should call <target>:refuses_action (player, <action>). <target> is the target of the action; it is you, because others are smirking at you. 'Player' is the current player, the one who is attempting to perform the action. <action> is the action the player is attempting, 'smirk'.",
    "",
    "In this case, you want to change your :tell verb to check whether its message contains the word 'smirk', and whether you are refusing smirks from the player who's talking. It also has to do two other things: (1) inform the player whose smirk was refused, and (2) call this:report_refusal, which tests whether you have refusal reporting turned on, and if so, reports the refusal to you. The call is this:report_refusal (<player>, <message>).",
    "",
    "    @verb me:tell this none this",
    "    @program me:tell",
    "      line = tostr (@args);",
    "      if (index (line, \"smirk\") &&",
    "          this:refuses_action (player, \"smirk\"))",
    "        player:tell (this.name, \" refuses your s m i r k.\");",
    "        this:report_refusal (player, \"You refused a s m i r k.\");",
    "      else",
    "        pass (@args);",
    "      endif",
    "    .",
    "",
    "The messages say 's m i r k' instead of 'smirk' to prevent an infinite :tell loop.",
    "",
    "It may help to study some examples. To see how whisper refusal works, read #3133:whisper. For page refusal, see #3133:receive_page and #3133:page_echo_msg. For mail refusal, #3133:receive_message. For move and accept refusal, #3133:moveto or #3133:accept (they are the same verb).",
    "",
    " - refusal data structures",
    "",
    "Refusal information is stored in four main properties, all lists.",
    "",
    "    .refused_origins    - who you are refusing actions from",
    "    .refused_actions    - for each, what actions you're refusing",
    "    .refused_until      - when the refusals expire",
    "    .refused_extra      - any further information about each refused action",
    "",
    "These properties are all readable and owned by Frand. You (or anyone) can see their values, but you can only change them by calling verbs for the purpose. The verbs are explained later on.",
    "",
    "Your .refused_origins property remembers who you are refusing actions from. It might have the value {#47, #34567} if you are refusing actions from Frand (#47) and Stupid_Jerk (#34567). If you are refusing actions by guests, it will have entries like \"xxP1Xw.nkQzft\". This weird string is a code word that stands for the guest's connection site; you are refusing actions not by a certain guest character, but by any guest who may connect from that site. The verb :player_to_refusal_origin (<player>) converts a player object to a refusal origin (either the same player object or a guest's site code) suitable to be stored in .refused_origins.",
    "",
    "Your .refused_actions property stores, for each origin in .refused_origins, a list of the actions you are refusing for that origin. Continuing the example from the last paragraph, if you are refusing page from Frand and page, whisper, and mail from Stupid_Jerk, then your .refused_actions has the value {{\"page\"}, {\"page\", \"whisper\", \"mail\"}}.",
    "",
    "Your .refused_until stores an expiration time for each refusal origin, in the form used by time(), the number of seconds since midnight, 1 January 1970, GMT. All actions that you are refusing from a given player expire at the same time. If you are refusing Frand until 19 December 1992, and Stupid_Jerk for seven years, your .refused_until might have the value {724763397, 928384392}.",
    "",
    "Your .refused_extra property stores any additional information needed for fancy refusals. It stores one piece of information for every action you are refusing from every player. In other words, .refused_extra contains a list of lists which are parallel to the lists in .refused_actions. None of the built-in refusals on #3133 is fancy, so for them, the extra piece of information is always 0. In the example, your .refused_extra has the value {{0}, {0, 0, 0}}. The next section explains how to use .refused_extra in fancy refusals.",
    "",
    "Another property, .default_refusal_time, stores the duration in seconds that a refusal lasts by default. This property is readable and owned by Frand. Its value is usually 604800, seven days. You can set it via the verb :set_default_refusal_time.",
    "",
    " - fancy refusable actions",
    "",
    "THIS SECTION IS NOT YET WRITTEN",
    "",
    " - selective refusal reporting",
    "",
    "If you have done '@refusal-reporting on', then you see a message when you refuse somebody else's action (for some actions). This reporting is done by the verb :report_refusal.",
    "",
    "    :report_refusal (<player>, <message>, ...)",
    "",
    "The first argument is the player whose action is refused, and the rest are concatenated to form the message that you see.",
    "",
    "You can override this verb if you want more selective refusal reporting. If you're refusing pages, for example, you might find that the refusal report is just as annoying as the original page--but you still don't want to turn it off. In that case, you might decide to give no more than one refusal report per minute, using code like this:",
    "",
    "    @property me.refusal_time 0",
    "    @property me.refusal_count 0",
    "    @verb me:report_refusal this none this",
    "    @program me:report_refusal",
    "      if (time() - this.refusal_time < 60)",
    "        this.refusal_count = this.refusal_count + 1;",
    "      else",
    "        if (this.refusal_count > 0)",
    "           pass (args [1], \"You've refused \", this.refusal_count+1,",
    "                 \" actions recently.\");",
    "        else",
    "          pass (@args);",
    "        endif",
    "        this.refusal_time = time();",
    "        this.refusal_count = 0;",
    "      endif",
    "    .",
    "",
    "The property that remembers whether refusal reporting is turned on is .report_refusal, which may have the values 0 or 1. The property is owned by Frand, so you can't change it directly.",
    "",
    " - refusal synonyms",
    "",
    "You can give a refusal more than one name by overriding the verb :translate_refusal_synonym. The verb takes one argument, a word from the command line, and it returns a list of refusal names that the word stands for. If the word is not a synonym, :translate_refusal_synonym should return the empty list, {}.",
    "",
    "    :translate_refusal_synonym (<word>) -> <list>",
    "",
    "If you want 'noise' to mean both page and whisper for you, then you'd write this. You need to pass(@args) to get the synonym 'all', which stands for all refusable actions. If you type '@refuse noises from Munchkin', the plural 's' is removed automatically, so you don't have to worry about that.",
    "",
    "    @verb me:translate_refusal_synonym this none this",
    "    @program me:translate_refusal_synonym",
    "      return pass(@args) ||",
    "             (args [1] == \"noise\") ? {\"page\", \"whisper\"} | {};",
    "    .",
    "",
    " - refusing actions by classes of players",
    "",
    "THIS SECTION IS NOT YET WRITTEN"
  };
  property "zombie-messages" (owner: HACKER, flags: "rc") = {"*forward*", "@unrmmail"};

  override aliases (owner: HACKER, flags: "rc") = {"Mail Commands Help Db"};
  override description (owner: HACKER, flags: "rc") = "This help database contains topics relating to the general use of the mail system.";
  override index_cache (owner: HACKER, flags: "r") = {"mail-index"};
  override object_size (owner: HACKER, flags: "r") = {36642, 1084848672};
endobject
