// automatically generated by the FlatBuffers compiler, do not modify
// ignore_for_file: unused_import, unused_field, unused_element, unused_local_variable

library moor_program;

import 'dart:typed_data' show Uint8List;
import 'package:flat_buffers/flat_buffers.dart' as fb;

import './moor_rpc_moor_common_generated.dart' as moor_common;
import './moor_rpc_moor_rpc_generated.dart' as moor_rpc;
import './moor_rpc_moor_var_generated.dart' as moor_var;

class StoredDeclType {
  final int value;
  const StoredDeclType._(this.value);

  factory StoredDeclType.fromValue(int value) {
    final result = values[value];
    if (result == null) {
      throw StateError('Invalid value $value for bit flag enum StoredDeclType');
    }
    return result;
  }

  static StoredDeclType? _createOrNull(int? value) =>
      value == null ? null : StoredDeclType.fromValue(value);

  static const int minValue = 0;
  static const int maxValue = 8;
  static bool containsValue(int value) => values.containsKey(value);

  static const StoredDeclType Global = StoredDeclType._(0);
  static const StoredDeclType Let = StoredDeclType._(1);
  static const StoredDeclType Assign = StoredDeclType._(2);
  static const StoredDeclType For = StoredDeclType._(3);
  static const StoredDeclType Unknown = StoredDeclType._(4);
  static const StoredDeclType Register = StoredDeclType._(5);
  static const StoredDeclType Except = StoredDeclType._(6);
  static const StoredDeclType WhileLabel = StoredDeclType._(7);
  static const StoredDeclType ForkLabel = StoredDeclType._(8);
  static const Map<int, StoredDeclType> values = {
    0: Global,
    1: Let,
    2: Assign,
    3: For,
    4: Unknown,
    5: Register,
    6: Except,
    7: WhileLabel,
    8: ForkLabel,
  };

  static const fb.Reader<StoredDeclType> reader = _StoredDeclTypeReader();

  @override
  String toString() {
    return 'StoredDeclType{value: $value}';
  }
}

class _StoredDeclTypeReader extends fb.Reader<StoredDeclType> {
  const _StoredDeclTypeReader();

  @override
  int get size => 1;

  @override
  StoredDeclType read(fb.BufferContext bc, int offset) =>
      StoredDeclType.fromValue(const fb.Uint8Reader().read(bc, offset));
}

class StoredVarNameUnionTypeId {
  final int value;
  const StoredVarNameUnionTypeId._(this.value);

  factory StoredVarNameUnionTypeId.fromValue(int value) {
    final result = values[value];
    if (result == null) {
      throw StateError(
        'Invalid value $value for bit flag enum StoredVarNameUnionTypeId',
      );
    }
    return result;
  }

  static StoredVarNameUnionTypeId? _createOrNull(int? value) =>
      value == null ? null : StoredVarNameUnionTypeId.fromValue(value);

  static const int minValue = 0;
  static const int maxValue = 2;
  static bool containsValue(int value) => values.containsKey(value);

  static const StoredVarNameUnionTypeId NONE = StoredVarNameUnionTypeId._(0);
  static const StoredVarNameUnionTypeId StoredNamedVar =
      StoredVarNameUnionTypeId._(1);
  static const StoredVarNameUnionTypeId StoredRegisterVar =
      StoredVarNameUnionTypeId._(2);
  static const Map<int, StoredVarNameUnionTypeId> values = {
    0: NONE,
    1: StoredNamedVar,
    2: StoredRegisterVar,
  };

  static const fb.Reader<StoredVarNameUnionTypeId> reader =
      _StoredVarNameUnionTypeIdReader();

  @override
  String toString() {
    return 'StoredVarNameUnionTypeId{value: $value}';
  }
}

class _StoredVarNameUnionTypeIdReader
    extends fb.Reader<StoredVarNameUnionTypeId> {
  const _StoredVarNameUnionTypeIdReader();

  @override
  int get size => 1;

  @override
  StoredVarNameUnionTypeId read(fb.BufferContext bc, int offset) =>
      StoredVarNameUnionTypeId.fromValue(
        const fb.Uint8Reader().read(bc, offset),
      );
}

class StoredScatterLabelUnionTypeId {
  final int value;
  const StoredScatterLabelUnionTypeId._(this.value);

  factory StoredScatterLabelUnionTypeId.fromValue(int value) {
    final result = values[value];
    if (result == null) {
      throw StateError(
        'Invalid value $value for bit flag enum StoredScatterLabelUnionTypeId',
      );
    }
    return result;
  }

  static StoredScatterLabelUnionTypeId? _createOrNull(int? value) =>
      value == null ? null : StoredScatterLabelUnionTypeId.fromValue(value);

  static const int minValue = 0;
  static const int maxValue = 3;
  static bool containsValue(int value) => values.containsKey(value);

  static const StoredScatterLabelUnionTypeId NONE =
      StoredScatterLabelUnionTypeId._(0);
  static const StoredScatterLabelUnionTypeId StoredScatterRequired =
      StoredScatterLabelUnionTypeId._(1);
  static const StoredScatterLabelUnionTypeId StoredScatterOptional =
      StoredScatterLabelUnionTypeId._(2);
  static const StoredScatterLabelUnionTypeId StoredScatterRest =
      StoredScatterLabelUnionTypeId._(3);
  static const Map<int, StoredScatterLabelUnionTypeId> values = {
    0: NONE,
    1: StoredScatterRequired,
    2: StoredScatterOptional,
    3: StoredScatterRest,
  };

  static const fb.Reader<StoredScatterLabelUnionTypeId> reader =
      _StoredScatterLabelUnionTypeIdReader();

  @override
  String toString() {
    return 'StoredScatterLabelUnionTypeId{value: $value}';
  }
}

class _StoredScatterLabelUnionTypeIdReader
    extends fb.Reader<StoredScatterLabelUnionTypeId> {
  const _StoredScatterLabelUnionTypeIdReader();

  @override
  int get size => 1;

  @override
  StoredScatterLabelUnionTypeId read(fb.BufferContext bc, int offset) =>
      StoredScatterLabelUnionTypeId.fromValue(
        const fb.Uint8Reader().read(bc, offset),
      );
}

class StoredProgramLanguageTypeId {
  final int value;
  const StoredProgramLanguageTypeId._(this.value);

  factory StoredProgramLanguageTypeId.fromValue(int value) {
    final result = values[value];
    if (result == null) {
      throw StateError(
        'Invalid value $value for bit flag enum StoredProgramLanguageTypeId',
      );
    }
    return result;
  }

  static StoredProgramLanguageTypeId? _createOrNull(int? value) =>
      value == null ? null : StoredProgramLanguageTypeId.fromValue(value);

  static const int minValue = 0;
  static const int maxValue = 1;
  static bool containsValue(int value) => values.containsKey(value);

  static const StoredProgramLanguageTypeId NONE = StoredProgramLanguageTypeId._(
    0,
  );
  static const StoredProgramLanguageTypeId StoredMooRProgram =
      StoredProgramLanguageTypeId._(1);
  static const Map<int, StoredProgramLanguageTypeId> values = {
    0: NONE,
    1: StoredMooRProgram,
  };

  static const fb.Reader<StoredProgramLanguageTypeId> reader =
      _StoredProgramLanguageTypeIdReader();

  @override
  String toString() {
    return 'StoredProgramLanguageTypeId{value: $value}';
  }
}

class _StoredProgramLanguageTypeIdReader
    extends fb.Reader<StoredProgramLanguageTypeId> {
  const _StoredProgramLanguageTypeIdReader();

  @override
  int get size => 1;

  @override
  StoredProgramLanguageTypeId read(fb.BufferContext bc, int offset) =>
      StoredProgramLanguageTypeId.fromValue(
        const fb.Uint8Reader().read(bc, offset),
      );
}

class StoredName {
  StoredName._(this._bc, this._bcOffset);
  factory StoredName(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<StoredName> reader = _StoredNameReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get offset => const fb.Uint16Reader().vTableGet(_bc, _bcOffset, 4, 0);
  int get scopeDepth => const fb.Uint8Reader().vTableGet(_bc, _bcOffset, 6, 0);
  int get scopeId => const fb.Uint16Reader().vTableGet(_bc, _bcOffset, 8, 0);

  @override
  String toString() {
    return 'StoredName{offset: ${offset}, scopeDepth: ${scopeDepth}, scopeId: ${scopeId}}';
  }
}

class _StoredNameReader extends fb.TableReader<StoredName> {
  const _StoredNameReader();

  @override
  StoredName createObject(fb.BufferContext bc, int offset) =>
      StoredName._(bc, offset);
}

class StoredNameBuilder {
  StoredNameBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(3);
  }

  int addOffset(int? offset) {
    fbBuilder.addUint16(0, offset);
    return fbBuilder.offset;
  }

  int addScopeDepth(int? scopeDepth) {
    fbBuilder.addUint8(1, scopeDepth);
    return fbBuilder.offset;
  }

  int addScopeId(int? scopeId) {
    fbBuilder.addUint16(2, scopeId);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class StoredNameObjectBuilder extends fb.ObjectBuilder {
  final int? _offset;
  final int? _scopeDepth;
  final int? _scopeId;

  StoredNameObjectBuilder({
    int? offset,
    int? scopeDepth,
    int? scopeId,
  }) : _offset = offset,
       _scopeDepth = scopeDepth,
       _scopeId = scopeId;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    fbBuilder.startTable(3);
    fbBuilder.addUint16(0, _offset);
    fbBuilder.addUint8(1, _scopeDepth);
    fbBuilder.addUint16(2, _scopeId);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class StoredJumpLabel {
  StoredJumpLabel._(this._bc, this._bcOffset);
  factory StoredJumpLabel(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<StoredJumpLabel> reader = _StoredJumpLabelReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get id => const fb.Uint16Reader().vTableGet(_bc, _bcOffset, 4, 0);
  int get position => const fb.Uint16Reader().vTableGet(_bc, _bcOffset, 6, 0);
  StoredName? get name =>
      StoredName.reader.vTableGetNullable(_bc, _bcOffset, 8);

  @override
  String toString() {
    return 'StoredJumpLabel{id: ${id}, position: ${position}, name: ${name}}';
  }
}

class _StoredJumpLabelReader extends fb.TableReader<StoredJumpLabel> {
  const _StoredJumpLabelReader();

  @override
  StoredJumpLabel createObject(fb.BufferContext bc, int offset) =>
      StoredJumpLabel._(bc, offset);
}

class StoredJumpLabelBuilder {
  StoredJumpLabelBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(3);
  }

  int addId(int? id) {
    fbBuilder.addUint16(0, id);
    return fbBuilder.offset;
  }

  int addPosition(int? position) {
    fbBuilder.addUint16(1, position);
    return fbBuilder.offset;
  }

  int addNameOffset(int? offset) {
    fbBuilder.addOffset(2, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class StoredJumpLabelObjectBuilder extends fb.ObjectBuilder {
  final int? _id;
  final int? _position;
  final StoredNameObjectBuilder? _name;

  StoredJumpLabelObjectBuilder({
    int? id,
    int? position,
    StoredNameObjectBuilder? name,
  }) : _id = id,
       _position = position,
       _name = name;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? nameOffset = _name?.getOrCreateOffset(fbBuilder);
    fbBuilder.startTable(3);
    fbBuilder.addUint16(0, _id);
    fbBuilder.addUint16(1, _position);
    fbBuilder.addOffset(2, nameOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class StoredNamedVar {
  StoredNamedVar._(this._bc, this._bcOffset);
  factory StoredNamedVar(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<StoredNamedVar> reader = _StoredNamedVarReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  moor_common.Symbol? get symbol =>
      moor_common.Symbol.reader.vTableGetNullable(_bc, _bcOffset, 4);

  @override
  String toString() {
    return 'StoredNamedVar{symbol: ${symbol}}';
  }
}

class _StoredNamedVarReader extends fb.TableReader<StoredNamedVar> {
  const _StoredNamedVarReader();

  @override
  StoredNamedVar createObject(fb.BufferContext bc, int offset) =>
      StoredNamedVar._(bc, offset);
}

class StoredNamedVarBuilder {
  StoredNamedVarBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(1);
  }

  int addSymbolOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class StoredNamedVarObjectBuilder extends fb.ObjectBuilder {
  final moor_common.SymbolObjectBuilder? _symbol;

  StoredNamedVarObjectBuilder({
    moor_common.SymbolObjectBuilder? symbol,
  }) : _symbol = symbol;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? symbolOffset = _symbol?.getOrCreateOffset(fbBuilder);
    fbBuilder.startTable(1);
    fbBuilder.addOffset(0, symbolOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class StoredRegisterVar {
  StoredRegisterVar._(this._bc, this._bcOffset);
  factory StoredRegisterVar(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<StoredRegisterVar> reader = _StoredRegisterVarReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get registerNum =>
      const fb.Uint16Reader().vTableGet(_bc, _bcOffset, 4, 0);

  @override
  String toString() {
    return 'StoredRegisterVar{registerNum: ${registerNum}}';
  }
}

class _StoredRegisterVarReader extends fb.TableReader<StoredRegisterVar> {
  const _StoredRegisterVarReader();

  @override
  StoredRegisterVar createObject(fb.BufferContext bc, int offset) =>
      StoredRegisterVar._(bc, offset);
}

class StoredRegisterVarBuilder {
  StoredRegisterVarBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(1);
  }

  int addRegisterNum(int? registerNum) {
    fbBuilder.addUint16(0, registerNum);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class StoredRegisterVarObjectBuilder extends fb.ObjectBuilder {
  final int? _registerNum;

  StoredRegisterVarObjectBuilder({
    int? registerNum,
  }) : _registerNum = registerNum;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    fbBuilder.startTable(1);
    fbBuilder.addUint16(0, _registerNum);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class StoredVariable {
  StoredVariable._(this._bc, this._bcOffset);
  factory StoredVariable(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<StoredVariable> reader = _StoredVariableReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get id => const fb.Uint16Reader().vTableGet(_bc, _bcOffset, 4, 0);
  int get scopeId => const fb.Uint16Reader().vTableGet(_bc, _bcOffset, 6, 0);
  StoredVarNameUnionTypeId? get varNameType =>
      StoredVarNameUnionTypeId._createOrNull(
        const fb.Uint8Reader().vTableGetNullable(_bc, _bcOffset, 8),
      );
  dynamic get varName {
    switch (varNameType?.value) {
      case 1:
        return StoredNamedVar.reader.vTableGetNullable(_bc, _bcOffset, 10);
      case 2:
        return StoredRegisterVar.reader.vTableGetNullable(_bc, _bcOffset, 10);
      default:
        return null;
    }
  }

  @override
  String toString() {
    return 'StoredVariable{id: ${id}, scopeId: ${scopeId}, varNameType: ${varNameType}, varName: ${varName}}';
  }
}

class _StoredVariableReader extends fb.TableReader<StoredVariable> {
  const _StoredVariableReader();

  @override
  StoredVariable createObject(fb.BufferContext bc, int offset) =>
      StoredVariable._(bc, offset);
}

class StoredVariableBuilder {
  StoredVariableBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(4);
  }

  int addId(int? id) {
    fbBuilder.addUint16(0, id);
    return fbBuilder.offset;
  }

  int addScopeId(int? scopeId) {
    fbBuilder.addUint16(1, scopeId);
    return fbBuilder.offset;
  }

  int addVarNameType(StoredVarNameUnionTypeId? varNameType) {
    fbBuilder.addUint8(2, varNameType?.value);
    return fbBuilder.offset;
  }

  int addVarNameOffset(int? offset) {
    fbBuilder.addOffset(3, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class StoredVariableObjectBuilder extends fb.ObjectBuilder {
  final int? _id;
  final int? _scopeId;
  final StoredVarNameUnionTypeId? _varNameType;
  final dynamic _varName;

  StoredVariableObjectBuilder({
    int? id,
    int? scopeId,
    StoredVarNameUnionTypeId? varNameType,
    dynamic varName,
  }) : _id = id,
       _scopeId = scopeId,
       _varNameType = varNameType,
       _varName = varName;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? varNameOffset = _varName?.getOrCreateOffset(fbBuilder);
    fbBuilder.startTable(4);
    fbBuilder.addUint16(0, _id);
    fbBuilder.addUint16(1, _scopeId);
    fbBuilder.addUint8(2, _varNameType?.value);
    fbBuilder.addOffset(3, varNameOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class StoredDecl {
  StoredDecl._(this._bc, this._bcOffset);
  factory StoredDecl(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<StoredDecl> reader = _StoredDeclReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  StoredDeclType get declType => StoredDeclType.fromValue(
    const fb.Uint8Reader().vTableGet(_bc, _bcOffset, 4, 0),
  );
  StoredVariable? get identifier =>
      StoredVariable.reader.vTableGetNullable(_bc, _bcOffset, 6);
  int get depth => const fb.Uint64Reader().vTableGet(_bc, _bcOffset, 8, 0);
  bool get constant =>
      const fb.BoolReader().vTableGet(_bc, _bcOffset, 10, false);
  int get scopeId => const fb.Uint16Reader().vTableGet(_bc, _bcOffset, 12, 0);

  @override
  String toString() {
    return 'StoredDecl{declType: ${declType}, identifier: ${identifier}, depth: ${depth}, constant: ${constant}, scopeId: ${scopeId}}';
  }
}

class _StoredDeclReader extends fb.TableReader<StoredDecl> {
  const _StoredDeclReader();

  @override
  StoredDecl createObject(fb.BufferContext bc, int offset) =>
      StoredDecl._(bc, offset);
}

class StoredDeclBuilder {
  StoredDeclBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(5);
  }

  int addDeclType(StoredDeclType? declType) {
    fbBuilder.addUint8(0, declType?.value);
    return fbBuilder.offset;
  }

  int addIdentifierOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }

  int addDepth(int? depth) {
    fbBuilder.addUint64(2, depth);
    return fbBuilder.offset;
  }

  int addConstant(bool? constant) {
    fbBuilder.addBool(3, constant);
    return fbBuilder.offset;
  }

  int addScopeId(int? scopeId) {
    fbBuilder.addUint16(4, scopeId);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class StoredDeclObjectBuilder extends fb.ObjectBuilder {
  final StoredDeclType? _declType;
  final StoredVariableObjectBuilder? _identifier;
  final int? _depth;
  final bool? _constant;
  final int? _scopeId;

  StoredDeclObjectBuilder({
    StoredDeclType? declType,
    StoredVariableObjectBuilder? identifier,
    int? depth,
    bool? constant,
    int? scopeId,
  }) : _declType = declType,
       _identifier = identifier,
       _depth = depth,
       _constant = constant,
       _scopeId = scopeId;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? identifierOffset = _identifier?.getOrCreateOffset(fbBuilder);
    fbBuilder.startTable(5);
    fbBuilder.addUint8(0, _declType?.value);
    fbBuilder.addOffset(1, identifierOffset);
    fbBuilder.addUint64(2, _depth);
    fbBuilder.addBool(3, _constant);
    fbBuilder.addUint16(4, _scopeId);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class StoredNameDeclPair {
  StoredNameDeclPair._(this._bc, this._bcOffset);
  factory StoredNameDeclPair(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<StoredNameDeclPair> reader =
      _StoredNameDeclPairReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  StoredName? get name =>
      StoredName.reader.vTableGetNullable(_bc, _bcOffset, 4);
  StoredDecl? get decl =>
      StoredDecl.reader.vTableGetNullable(_bc, _bcOffset, 6);

  @override
  String toString() {
    return 'StoredNameDeclPair{name: ${name}, decl: ${decl}}';
  }
}

class _StoredNameDeclPairReader extends fb.TableReader<StoredNameDeclPair> {
  const _StoredNameDeclPairReader();

  @override
  StoredNameDeclPair createObject(fb.BufferContext bc, int offset) =>
      StoredNameDeclPair._(bc, offset);
}

class StoredNameDeclPairBuilder {
  StoredNameDeclPairBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(2);
  }

  int addNameOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }

  int addDeclOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class StoredNameDeclPairObjectBuilder extends fb.ObjectBuilder {
  final StoredNameObjectBuilder? _name;
  final StoredDeclObjectBuilder? _decl;

  StoredNameDeclPairObjectBuilder({
    StoredNameObjectBuilder? name,
    StoredDeclObjectBuilder? decl,
  }) : _name = name,
       _decl = decl;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? nameOffset = _name?.getOrCreateOffset(fbBuilder);
    final int? declOffset = _decl?.getOrCreateOffset(fbBuilder);
    fbBuilder.startTable(2);
    fbBuilder.addOffset(0, nameOffset);
    fbBuilder.addOffset(1, declOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class StoredNames {
  StoredNames._(this._bc, this._bcOffset);
  factory StoredNames(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<StoredNames> reader = _StoredNamesReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get globalWidth =>
      const fb.Uint64Reader().vTableGet(_bc, _bcOffset, 4, 0);
  List<StoredNameDeclPair>? get decls =>
      const fb.ListReader<StoredNameDeclPair>(
        StoredNameDeclPair.reader,
      ).vTableGetNullable(_bc, _bcOffset, 6);

  @override
  String toString() {
    return 'StoredNames{globalWidth: ${globalWidth}, decls: ${decls}}';
  }
}

class _StoredNamesReader extends fb.TableReader<StoredNames> {
  const _StoredNamesReader();

  @override
  StoredNames createObject(fb.BufferContext bc, int offset) =>
      StoredNames._(bc, offset);
}

class StoredNamesBuilder {
  StoredNamesBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(2);
  }

  int addGlobalWidth(int? globalWidth) {
    fbBuilder.addUint64(0, globalWidth);
    return fbBuilder.offset;
  }

  int addDeclsOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class StoredNamesObjectBuilder extends fb.ObjectBuilder {
  final int? _globalWidth;
  final List<StoredNameDeclPairObjectBuilder>? _decls;

  StoredNamesObjectBuilder({
    int? globalWidth,
    List<StoredNameDeclPairObjectBuilder>? decls,
  }) : _globalWidth = globalWidth,
       _decls = decls;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? declsOffset = _decls == null
        ? null
        : fbBuilder.writeList(
            _decls!.map((b) => b.getOrCreateOffset(fbBuilder)).toList(),
          );
    fbBuilder.startTable(2);
    fbBuilder.addUint64(0, _globalWidth);
    fbBuilder.addOffset(1, declsOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class StoredScatterRequired {
  StoredScatterRequired._(this._bc, this._bcOffset);
  factory StoredScatterRequired(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<StoredScatterRequired> reader =
      _StoredScatterRequiredReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  StoredName? get name =>
      StoredName.reader.vTableGetNullable(_bc, _bcOffset, 4);

  @override
  String toString() {
    return 'StoredScatterRequired{name: ${name}}';
  }
}

class _StoredScatterRequiredReader
    extends fb.TableReader<StoredScatterRequired> {
  const _StoredScatterRequiredReader();

  @override
  StoredScatterRequired createObject(fb.BufferContext bc, int offset) =>
      StoredScatterRequired._(bc, offset);
}

class StoredScatterRequiredBuilder {
  StoredScatterRequiredBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(1);
  }

  int addNameOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class StoredScatterRequiredObjectBuilder extends fb.ObjectBuilder {
  final StoredNameObjectBuilder? _name;

  StoredScatterRequiredObjectBuilder({
    StoredNameObjectBuilder? name,
  }) : _name = name;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? nameOffset = _name?.getOrCreateOffset(fbBuilder);
    fbBuilder.startTable(1);
    fbBuilder.addOffset(0, nameOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class StoredScatterOptional {
  StoredScatterOptional._(this._bc, this._bcOffset);
  factory StoredScatterOptional(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<StoredScatterOptional> reader =
      _StoredScatterOptionalReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  StoredName? get name =>
      StoredName.reader.vTableGetNullable(_bc, _bcOffset, 4);
  int get defaultLabel =>
      const fb.Uint16Reader().vTableGet(_bc, _bcOffset, 6, 0);
  bool get hasDefault =>
      const fb.BoolReader().vTableGet(_bc, _bcOffset, 8, false);

  @override
  String toString() {
    return 'StoredScatterOptional{name: ${name}, defaultLabel: ${defaultLabel}, hasDefault: ${hasDefault}}';
  }
}

class _StoredScatterOptionalReader
    extends fb.TableReader<StoredScatterOptional> {
  const _StoredScatterOptionalReader();

  @override
  StoredScatterOptional createObject(fb.BufferContext bc, int offset) =>
      StoredScatterOptional._(bc, offset);
}

class StoredScatterOptionalBuilder {
  StoredScatterOptionalBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(3);
  }

  int addNameOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }

  int addDefaultLabel(int? defaultLabel) {
    fbBuilder.addUint16(1, defaultLabel);
    return fbBuilder.offset;
  }

  int addHasDefault(bool? hasDefault) {
    fbBuilder.addBool(2, hasDefault);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class StoredScatterOptionalObjectBuilder extends fb.ObjectBuilder {
  final StoredNameObjectBuilder? _name;
  final int? _defaultLabel;
  final bool? _hasDefault;

  StoredScatterOptionalObjectBuilder({
    StoredNameObjectBuilder? name,
    int? defaultLabel,
    bool? hasDefault,
  }) : _name = name,
       _defaultLabel = defaultLabel,
       _hasDefault = hasDefault;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? nameOffset = _name?.getOrCreateOffset(fbBuilder);
    fbBuilder.startTable(3);
    fbBuilder.addOffset(0, nameOffset);
    fbBuilder.addUint16(1, _defaultLabel);
    fbBuilder.addBool(2, _hasDefault);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class StoredScatterRest {
  StoredScatterRest._(this._bc, this._bcOffset);
  factory StoredScatterRest(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<StoredScatterRest> reader = _StoredScatterRestReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  StoredName? get name =>
      StoredName.reader.vTableGetNullable(_bc, _bcOffset, 4);

  @override
  String toString() {
    return 'StoredScatterRest{name: ${name}}';
  }
}

class _StoredScatterRestReader extends fb.TableReader<StoredScatterRest> {
  const _StoredScatterRestReader();

  @override
  StoredScatterRest createObject(fb.BufferContext bc, int offset) =>
      StoredScatterRest._(bc, offset);
}

class StoredScatterRestBuilder {
  StoredScatterRestBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(1);
  }

  int addNameOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class StoredScatterRestObjectBuilder extends fb.ObjectBuilder {
  final StoredNameObjectBuilder? _name;

  StoredScatterRestObjectBuilder({
    StoredNameObjectBuilder? name,
  }) : _name = name;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? nameOffset = _name?.getOrCreateOffset(fbBuilder);
    fbBuilder.startTable(1);
    fbBuilder.addOffset(0, nameOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class StoredScatterLabel {
  StoredScatterLabel._(this._bc, this._bcOffset);
  factory StoredScatterLabel(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<StoredScatterLabel> reader =
      _StoredScatterLabelReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  StoredScatterLabelUnionTypeId? get labelType =>
      StoredScatterLabelUnionTypeId._createOrNull(
        const fb.Uint8Reader().vTableGetNullable(_bc, _bcOffset, 4),
      );
  dynamic get label {
    switch (labelType?.value) {
      case 1:
        return StoredScatterRequired.reader.vTableGetNullable(
          _bc,
          _bcOffset,
          6,
        );
      case 2:
        return StoredScatterOptional.reader.vTableGetNullable(
          _bc,
          _bcOffset,
          6,
        );
      case 3:
        return StoredScatterRest.reader.vTableGetNullable(_bc, _bcOffset, 6);
      default:
        return null;
    }
  }

  @override
  String toString() {
    return 'StoredScatterLabel{labelType: ${labelType}, label: ${label}}';
  }
}

class _StoredScatterLabelReader extends fb.TableReader<StoredScatterLabel> {
  const _StoredScatterLabelReader();

  @override
  StoredScatterLabel createObject(fb.BufferContext bc, int offset) =>
      StoredScatterLabel._(bc, offset);
}

class StoredScatterLabelBuilder {
  StoredScatterLabelBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(2);
  }

  int addLabelType(StoredScatterLabelUnionTypeId? labelType) {
    fbBuilder.addUint8(0, labelType?.value);
    return fbBuilder.offset;
  }

  int addLabelOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class StoredScatterLabelObjectBuilder extends fb.ObjectBuilder {
  final StoredScatterLabelUnionTypeId? _labelType;
  final dynamic _label;

  StoredScatterLabelObjectBuilder({
    StoredScatterLabelUnionTypeId? labelType,
    dynamic label,
  }) : _labelType = labelType,
       _label = label;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? labelOffset = _label?.getOrCreateOffset(fbBuilder);
    fbBuilder.startTable(2);
    fbBuilder.addUint8(0, _labelType?.value);
    fbBuilder.addOffset(1, labelOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class StoredScatterArgs {
  StoredScatterArgs._(this._bc, this._bcOffset);
  factory StoredScatterArgs(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<StoredScatterArgs> reader = _StoredScatterArgsReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  List<StoredScatterLabel>? get labels =>
      const fb.ListReader<StoredScatterLabel>(
        StoredScatterLabel.reader,
      ).vTableGetNullable(_bc, _bcOffset, 4);
  int get done => const fb.Uint16Reader().vTableGet(_bc, _bcOffset, 6, 0);

  @override
  String toString() {
    return 'StoredScatterArgs{labels: ${labels}, done: ${done}}';
  }
}

class _StoredScatterArgsReader extends fb.TableReader<StoredScatterArgs> {
  const _StoredScatterArgsReader();

  @override
  StoredScatterArgs createObject(fb.BufferContext bc, int offset) =>
      StoredScatterArgs._(bc, offset);
}

class StoredScatterArgsBuilder {
  StoredScatterArgsBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(2);
  }

  int addLabelsOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }

  int addDone(int? done) {
    fbBuilder.addUint16(1, done);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class StoredScatterArgsObjectBuilder extends fb.ObjectBuilder {
  final List<StoredScatterLabelObjectBuilder>? _labels;
  final int? _done;

  StoredScatterArgsObjectBuilder({
    List<StoredScatterLabelObjectBuilder>? labels,
    int? done,
  }) : _labels = labels,
       _done = done;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? labelsOffset = _labels == null
        ? null
        : fbBuilder.writeList(
            _labels!.map((b) => b.getOrCreateOffset(fbBuilder)).toList(),
          );
    fbBuilder.startTable(2);
    fbBuilder.addOffset(0, labelsOffset);
    fbBuilder.addUint16(1, _done);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class StoredForSequenceOperand {
  StoredForSequenceOperand._(this._bc, this._bcOffset);
  factory StoredForSequenceOperand(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<StoredForSequenceOperand> reader =
      _StoredForSequenceOperandReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  StoredName? get valueBind =>
      StoredName.reader.vTableGetNullable(_bc, _bcOffset, 4);
  StoredName? get keyBind =>
      StoredName.reader.vTableGetNullable(_bc, _bcOffset, 6);
  int get endLabel => const fb.Uint16Reader().vTableGet(_bc, _bcOffset, 8, 0);
  int get environmentWidth =>
      const fb.Uint16Reader().vTableGet(_bc, _bcOffset, 10, 0);

  @override
  String toString() {
    return 'StoredForSequenceOperand{valueBind: ${valueBind}, keyBind: ${keyBind}, endLabel: ${endLabel}, environmentWidth: ${environmentWidth}}';
  }
}

class _StoredForSequenceOperandReader
    extends fb.TableReader<StoredForSequenceOperand> {
  const _StoredForSequenceOperandReader();

  @override
  StoredForSequenceOperand createObject(fb.BufferContext bc, int offset) =>
      StoredForSequenceOperand._(bc, offset);
}

class StoredForSequenceOperandBuilder {
  StoredForSequenceOperandBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(4);
  }

  int addValueBindOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }

  int addKeyBindOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }

  int addEndLabel(int? endLabel) {
    fbBuilder.addUint16(2, endLabel);
    return fbBuilder.offset;
  }

  int addEnvironmentWidth(int? environmentWidth) {
    fbBuilder.addUint16(3, environmentWidth);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class StoredForSequenceOperandObjectBuilder extends fb.ObjectBuilder {
  final StoredNameObjectBuilder? _valueBind;
  final StoredNameObjectBuilder? _keyBind;
  final int? _endLabel;
  final int? _environmentWidth;

  StoredForSequenceOperandObjectBuilder({
    StoredNameObjectBuilder? valueBind,
    StoredNameObjectBuilder? keyBind,
    int? endLabel,
    int? environmentWidth,
  }) : _valueBind = valueBind,
       _keyBind = keyBind,
       _endLabel = endLabel,
       _environmentWidth = environmentWidth;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? valueBindOffset = _valueBind?.getOrCreateOffset(fbBuilder);
    final int? keyBindOffset = _keyBind?.getOrCreateOffset(fbBuilder);
    fbBuilder.startTable(4);
    fbBuilder.addOffset(0, valueBindOffset);
    fbBuilder.addOffset(1, keyBindOffset);
    fbBuilder.addUint16(2, _endLabel);
    fbBuilder.addUint16(3, _environmentWidth);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class StoredForRangeOperand {
  StoredForRangeOperand._(this._bc, this._bcOffset);
  factory StoredForRangeOperand(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<StoredForRangeOperand> reader =
      _StoredForRangeOperandReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  StoredName? get loopVariable =>
      StoredName.reader.vTableGetNullable(_bc, _bcOffset, 4);
  int get endLabel => const fb.Uint16Reader().vTableGet(_bc, _bcOffset, 6, 0);
  int get environmentWidth =>
      const fb.Uint16Reader().vTableGet(_bc, _bcOffset, 8, 0);

  @override
  String toString() {
    return 'StoredForRangeOperand{loopVariable: ${loopVariable}, endLabel: ${endLabel}, environmentWidth: ${environmentWidth}}';
  }
}

class _StoredForRangeOperandReader
    extends fb.TableReader<StoredForRangeOperand> {
  const _StoredForRangeOperandReader();

  @override
  StoredForRangeOperand createObject(fb.BufferContext bc, int offset) =>
      StoredForRangeOperand._(bc, offset);
}

class StoredForRangeOperandBuilder {
  StoredForRangeOperandBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(3);
  }

  int addLoopVariableOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }

  int addEndLabel(int? endLabel) {
    fbBuilder.addUint16(1, endLabel);
    return fbBuilder.offset;
  }

  int addEnvironmentWidth(int? environmentWidth) {
    fbBuilder.addUint16(2, environmentWidth);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class StoredForRangeOperandObjectBuilder extends fb.ObjectBuilder {
  final StoredNameObjectBuilder? _loopVariable;
  final int? _endLabel;
  final int? _environmentWidth;

  StoredForRangeOperandObjectBuilder({
    StoredNameObjectBuilder? loopVariable,
    int? endLabel,
    int? environmentWidth,
  }) : _loopVariable = loopVariable,
       _endLabel = endLabel,
       _environmentWidth = environmentWidth;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? loopVariableOffset = _loopVariable?.getOrCreateOffset(fbBuilder);
    fbBuilder.startTable(3);
    fbBuilder.addOffset(0, loopVariableOffset);
    fbBuilder.addUint16(1, _endLabel);
    fbBuilder.addUint16(2, _environmentWidth);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class StoredRangeComprehend {
  StoredRangeComprehend._(this._bc, this._bcOffset);
  factory StoredRangeComprehend(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<StoredRangeComprehend> reader =
      _StoredRangeComprehendReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  StoredName? get position =>
      StoredName.reader.vTableGetNullable(_bc, _bcOffset, 4);
  StoredName? get endOfRangeRegister =>
      StoredName.reader.vTableGetNullable(_bc, _bcOffset, 6);
  int get endLabel => const fb.Uint16Reader().vTableGet(_bc, _bcOffset, 8, 0);

  @override
  String toString() {
    return 'StoredRangeComprehend{position: ${position}, endOfRangeRegister: ${endOfRangeRegister}, endLabel: ${endLabel}}';
  }
}

class _StoredRangeComprehendReader
    extends fb.TableReader<StoredRangeComprehend> {
  const _StoredRangeComprehendReader();

  @override
  StoredRangeComprehend createObject(fb.BufferContext bc, int offset) =>
      StoredRangeComprehend._(bc, offset);
}

class StoredRangeComprehendBuilder {
  StoredRangeComprehendBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(3);
  }

  int addPositionOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }

  int addEndOfRangeRegisterOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }

  int addEndLabel(int? endLabel) {
    fbBuilder.addUint16(2, endLabel);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class StoredRangeComprehendObjectBuilder extends fb.ObjectBuilder {
  final StoredNameObjectBuilder? _position;
  final StoredNameObjectBuilder? _endOfRangeRegister;
  final int? _endLabel;

  StoredRangeComprehendObjectBuilder({
    StoredNameObjectBuilder? position,
    StoredNameObjectBuilder? endOfRangeRegister,
    int? endLabel,
  }) : _position = position,
       _endOfRangeRegister = endOfRangeRegister,
       _endLabel = endLabel;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? positionOffset = _position?.getOrCreateOffset(fbBuilder);
    final int? endOfRangeRegisterOffset = _endOfRangeRegister
        ?.getOrCreateOffset(fbBuilder);
    fbBuilder.startTable(3);
    fbBuilder.addOffset(0, positionOffset);
    fbBuilder.addOffset(1, endOfRangeRegisterOffset);
    fbBuilder.addUint16(2, _endLabel);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class StoredListComprehend {
  StoredListComprehend._(this._bc, this._bcOffset);
  factory StoredListComprehend(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<StoredListComprehend> reader =
      _StoredListComprehendReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  StoredName? get positionRegister =>
      StoredName.reader.vTableGetNullable(_bc, _bcOffset, 4);
  StoredName? get listRegister =>
      StoredName.reader.vTableGetNullable(_bc, _bcOffset, 6);
  StoredName? get itemVariable =>
      StoredName.reader.vTableGetNullable(_bc, _bcOffset, 8);
  int get endLabel => const fb.Uint16Reader().vTableGet(_bc, _bcOffset, 10, 0);

  @override
  String toString() {
    return 'StoredListComprehend{positionRegister: ${positionRegister}, listRegister: ${listRegister}, itemVariable: ${itemVariable}, endLabel: ${endLabel}}';
  }
}

class _StoredListComprehendReader extends fb.TableReader<StoredListComprehend> {
  const _StoredListComprehendReader();

  @override
  StoredListComprehend createObject(fb.BufferContext bc, int offset) =>
      StoredListComprehend._(bc, offset);
}

class StoredListComprehendBuilder {
  StoredListComprehendBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(4);
  }

  int addPositionRegisterOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }

  int addListRegisterOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }

  int addItemVariableOffset(int? offset) {
    fbBuilder.addOffset(2, offset);
    return fbBuilder.offset;
  }

  int addEndLabel(int? endLabel) {
    fbBuilder.addUint16(3, endLabel);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class StoredListComprehendObjectBuilder extends fb.ObjectBuilder {
  final StoredNameObjectBuilder? _positionRegister;
  final StoredNameObjectBuilder? _listRegister;
  final StoredNameObjectBuilder? _itemVariable;
  final int? _endLabel;

  StoredListComprehendObjectBuilder({
    StoredNameObjectBuilder? positionRegister,
    StoredNameObjectBuilder? listRegister,
    StoredNameObjectBuilder? itemVariable,
    int? endLabel,
  }) : _positionRegister = positionRegister,
       _listRegister = listRegister,
       _itemVariable = itemVariable,
       _endLabel = endLabel;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? positionRegisterOffset = _positionRegister?.getOrCreateOffset(
      fbBuilder,
    );
    final int? listRegisterOffset = _listRegister?.getOrCreateOffset(fbBuilder);
    final int? itemVariableOffset = _itemVariable?.getOrCreateOffset(fbBuilder);
    fbBuilder.startTable(4);
    fbBuilder.addOffset(0, positionRegisterOffset);
    fbBuilder.addOffset(1, listRegisterOffset);
    fbBuilder.addOffset(2, itemVariableOffset);
    fbBuilder.addUint16(3, _endLabel);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class StoredErrorOperand {
  StoredErrorOperand._(this._bc, this._bcOffset);
  factory StoredErrorOperand(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<StoredErrorOperand> reader =
      _StoredErrorOperandReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get discriminant =>
      const fb.Uint8Reader().vTableGet(_bc, _bcOffset, 4, 0);
  String? get symbol =>
      const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 6);

  @override
  String toString() {
    return 'StoredErrorOperand{discriminant: ${discriminant}, symbol: ${symbol}}';
  }
}

class _StoredErrorOperandReader extends fb.TableReader<StoredErrorOperand> {
  const _StoredErrorOperandReader();

  @override
  StoredErrorOperand createObject(fb.BufferContext bc, int offset) =>
      StoredErrorOperand._(bc, offset);
}

class StoredErrorOperandBuilder {
  StoredErrorOperandBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(2);
  }

  int addDiscriminant(int? discriminant) {
    fbBuilder.addUint8(0, discriminant);
    return fbBuilder.offset;
  }

  int addSymbolOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class StoredErrorOperandObjectBuilder extends fb.ObjectBuilder {
  final int? _discriminant;
  final String? _symbol;

  StoredErrorOperandObjectBuilder({
    int? discriminant,
    String? symbol,
  }) : _discriminant = discriminant,
       _symbol = symbol;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? symbolOffset = _symbol == null
        ? null
        : fbBuilder.writeString(_symbol!);
    fbBuilder.startTable(2);
    fbBuilder.addUint8(0, _discriminant);
    fbBuilder.addOffset(1, symbolOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class ForkVector {
  ForkVector._(this._bc, this._bcOffset);
  factory ForkVector(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<ForkVector> reader = _ForkVectorReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get offset => const fb.Uint64Reader().vTableGet(_bc, _bcOffset, 4, 0);
  List<int>? get opcodes => const fb.ListReader<int>(
    fb.Uint16Reader(),
  ).vTableGetNullable(_bc, _bcOffset, 6);

  @override
  String toString() {
    return 'ForkVector{offset: ${offset}, opcodes: ${opcodes}}';
  }
}

class _ForkVectorReader extends fb.TableReader<ForkVector> {
  const _ForkVectorReader();

  @override
  ForkVector createObject(fb.BufferContext bc, int offset) =>
      ForkVector._(bc, offset);
}

class ForkVectorBuilder {
  ForkVectorBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(2);
  }

  int addOffset(int? offset) {
    fbBuilder.addUint64(0, offset);
    return fbBuilder.offset;
  }

  int addOpcodesOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class ForkVectorObjectBuilder extends fb.ObjectBuilder {
  final int? _offset;
  final List<int>? _opcodes;

  ForkVectorObjectBuilder({
    int? offset,
    List<int>? opcodes,
  }) : _offset = offset,
       _opcodes = opcodes;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? opcodesOffset = _opcodes == null
        ? null
        : fbBuilder.writeListUint16(_opcodes!);
    fbBuilder.startTable(2);
    fbBuilder.addUint64(0, _offset);
    fbBuilder.addOffset(1, opcodesOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class StoredMooRprogram {
  StoredMooRprogram._(this._bc, this._bcOffset);
  factory StoredMooRprogram(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<StoredMooRprogram> reader = _StoredMooRprogramReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get version => const fb.Uint16Reader().vTableGet(_bc, _bcOffset, 4, 0);
  int get builtinSignature =>
      const fb.Uint64Reader().vTableGet(_bc, _bcOffset, 6, 0);
  List<int>? get mainVector => const fb.ListReader<int>(
    fb.Uint16Reader(),
  ).vTableGetNullable(_bc, _bcOffset, 8);
  List<ForkVector>? get forkVectors => const fb.ListReader<ForkVector>(
    ForkVector.reader,
  ).vTableGetNullable(_bc, _bcOffset, 10);
  List<moor_var.Var>? get literals => const fb.ListReader<moor_var.Var>(
    moor_var.Var.reader,
  ).vTableGetNullable(_bc, _bcOffset, 12);
  List<StoredJumpLabel>? get jumpLabels => const fb.ListReader<StoredJumpLabel>(
    StoredJumpLabel.reader,
  ).vTableGetNullable(_bc, _bcOffset, 14);
  StoredNames? get varNames =>
      StoredNames.reader.vTableGetNullable(_bc, _bcOffset, 16);
  List<StoredScatterArgs>? get scatterTables =>
      const fb.ListReader<StoredScatterArgs>(
        StoredScatterArgs.reader,
      ).vTableGetNullable(_bc, _bcOffset, 18);
  List<StoredForSequenceOperand>? get forSequenceOperands =>
      const fb.ListReader<StoredForSequenceOperand>(
        StoredForSequenceOperand.reader,
      ).vTableGetNullable(_bc, _bcOffset, 20);
  List<StoredForRangeOperand>? get forRangeOperands =>
      const fb.ListReader<StoredForRangeOperand>(
        StoredForRangeOperand.reader,
      ).vTableGetNullable(_bc, _bcOffset, 22);
  List<StoredRangeComprehend>? get rangeComprehensions =>
      const fb.ListReader<StoredRangeComprehend>(
        StoredRangeComprehend.reader,
      ).vTableGetNullable(_bc, _bcOffset, 24);
  List<StoredListComprehend>? get listComprehensions =>
      const fb.ListReader<StoredListComprehend>(
        StoredListComprehend.reader,
      ).vTableGetNullable(_bc, _bcOffset, 26);
  List<StoredErrorOperand>? get errorOperandsFull =>
      const fb.ListReader<StoredErrorOperand>(
        StoredErrorOperand.reader,
      ).vTableGetNullable(_bc, _bcOffset, 28);
  List<StoredMooRprogram>? get lambdaPrograms =>
      const fb.ListReader<StoredMooRprogram>(
        StoredMooRprogram.reader,
      ).vTableGetNullable(_bc, _bcOffset, 30);
  List<LineSpan>? get lineNumberSpans => const fb.ListReader<LineSpan>(
    LineSpan.reader,
  ).vTableGetNullable(_bc, _bcOffset, 32);
  List<ForkLineSpans>? get forkLineNumberSpans =>
      const fb.ListReader<ForkLineSpans>(
        ForkLineSpans.reader,
      ).vTableGetNullable(_bc, _bcOffset, 34);

  @override
  String toString() {
    return 'StoredMooRprogram{version: ${version}, builtinSignature: ${builtinSignature}, mainVector: ${mainVector}, forkVectors: ${forkVectors}, literals: ${literals}, jumpLabels: ${jumpLabels}, varNames: ${varNames}, scatterTables: ${scatterTables}, forSequenceOperands: ${forSequenceOperands}, forRangeOperands: ${forRangeOperands}, rangeComprehensions: ${rangeComprehensions}, listComprehensions: ${listComprehensions}, errorOperandsFull: ${errorOperandsFull}, lambdaPrograms: ${lambdaPrograms}, lineNumberSpans: ${lineNumberSpans}, forkLineNumberSpans: ${forkLineNumberSpans}}';
  }
}

class _StoredMooRprogramReader extends fb.TableReader<StoredMooRprogram> {
  const _StoredMooRprogramReader();

  @override
  StoredMooRprogram createObject(fb.BufferContext bc, int offset) =>
      StoredMooRprogram._(bc, offset);
}

class StoredMooRprogramBuilder {
  StoredMooRprogramBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(16);
  }

  int addVersion(int? version) {
    fbBuilder.addUint16(0, version);
    return fbBuilder.offset;
  }

  int addBuiltinSignature(int? builtinSignature) {
    fbBuilder.addUint64(1, builtinSignature);
    return fbBuilder.offset;
  }

  int addMainVectorOffset(int? offset) {
    fbBuilder.addOffset(2, offset);
    return fbBuilder.offset;
  }

  int addForkVectorsOffset(int? offset) {
    fbBuilder.addOffset(3, offset);
    return fbBuilder.offset;
  }

  int addLiteralsOffset(int? offset) {
    fbBuilder.addOffset(4, offset);
    return fbBuilder.offset;
  }

  int addJumpLabelsOffset(int? offset) {
    fbBuilder.addOffset(5, offset);
    return fbBuilder.offset;
  }

  int addVarNamesOffset(int? offset) {
    fbBuilder.addOffset(6, offset);
    return fbBuilder.offset;
  }

  int addScatterTablesOffset(int? offset) {
    fbBuilder.addOffset(7, offset);
    return fbBuilder.offset;
  }

  int addForSequenceOperandsOffset(int? offset) {
    fbBuilder.addOffset(8, offset);
    return fbBuilder.offset;
  }

  int addForRangeOperandsOffset(int? offset) {
    fbBuilder.addOffset(9, offset);
    return fbBuilder.offset;
  }

  int addRangeComprehensionsOffset(int? offset) {
    fbBuilder.addOffset(10, offset);
    return fbBuilder.offset;
  }

  int addListComprehensionsOffset(int? offset) {
    fbBuilder.addOffset(11, offset);
    return fbBuilder.offset;
  }

  int addErrorOperandsFullOffset(int? offset) {
    fbBuilder.addOffset(12, offset);
    return fbBuilder.offset;
  }

  int addLambdaProgramsOffset(int? offset) {
    fbBuilder.addOffset(13, offset);
    return fbBuilder.offset;
  }

  int addLineNumberSpansOffset(int? offset) {
    fbBuilder.addOffset(14, offset);
    return fbBuilder.offset;
  }

  int addForkLineNumberSpansOffset(int? offset) {
    fbBuilder.addOffset(15, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class StoredMooRprogramObjectBuilder extends fb.ObjectBuilder {
  final int? _version;
  final int? _builtinSignature;
  final List<int>? _mainVector;
  final List<ForkVectorObjectBuilder>? _forkVectors;
  final List<moor_var.VarObjectBuilder>? _literals;
  final List<StoredJumpLabelObjectBuilder>? _jumpLabels;
  final StoredNamesObjectBuilder? _varNames;
  final List<StoredScatterArgsObjectBuilder>? _scatterTables;
  final List<StoredForSequenceOperandObjectBuilder>? _forSequenceOperands;
  final List<StoredForRangeOperandObjectBuilder>? _forRangeOperands;
  final List<StoredRangeComprehendObjectBuilder>? _rangeComprehensions;
  final List<StoredListComprehendObjectBuilder>? _listComprehensions;
  final List<StoredErrorOperandObjectBuilder>? _errorOperandsFull;
  final List<StoredMooRprogramObjectBuilder>? _lambdaPrograms;
  final List<LineSpanObjectBuilder>? _lineNumberSpans;
  final List<ForkLineSpansObjectBuilder>? _forkLineNumberSpans;

  StoredMooRprogramObjectBuilder({
    int? version,
    int? builtinSignature,
    List<int>? mainVector,
    List<ForkVectorObjectBuilder>? forkVectors,
    List<moor_var.VarObjectBuilder>? literals,
    List<StoredJumpLabelObjectBuilder>? jumpLabels,
    StoredNamesObjectBuilder? varNames,
    List<StoredScatterArgsObjectBuilder>? scatterTables,
    List<StoredForSequenceOperandObjectBuilder>? forSequenceOperands,
    List<StoredForRangeOperandObjectBuilder>? forRangeOperands,
    List<StoredRangeComprehendObjectBuilder>? rangeComprehensions,
    List<StoredListComprehendObjectBuilder>? listComprehensions,
    List<StoredErrorOperandObjectBuilder>? errorOperandsFull,
    List<StoredMooRprogramObjectBuilder>? lambdaPrograms,
    List<LineSpanObjectBuilder>? lineNumberSpans,
    List<ForkLineSpansObjectBuilder>? forkLineNumberSpans,
  }) : _version = version,
       _builtinSignature = builtinSignature,
       _mainVector = mainVector,
       _forkVectors = forkVectors,
       _literals = literals,
       _jumpLabels = jumpLabels,
       _varNames = varNames,
       _scatterTables = scatterTables,
       _forSequenceOperands = forSequenceOperands,
       _forRangeOperands = forRangeOperands,
       _rangeComprehensions = rangeComprehensions,
       _listComprehensions = listComprehensions,
       _errorOperandsFull = errorOperandsFull,
       _lambdaPrograms = lambdaPrograms,
       _lineNumberSpans = lineNumberSpans,
       _forkLineNumberSpans = forkLineNumberSpans;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? mainVectorOffset = _mainVector == null
        ? null
        : fbBuilder.writeListUint16(_mainVector!);
    final int? forkVectorsOffset = _forkVectors == null
        ? null
        : fbBuilder.writeList(
            _forkVectors!.map((b) => b.getOrCreateOffset(fbBuilder)).toList(),
          );
    final int? literalsOffset = _literals == null
        ? null
        : fbBuilder.writeList(
            _literals!.map((b) => b.getOrCreateOffset(fbBuilder)).toList(),
          );
    final int? jumpLabelsOffset = _jumpLabels == null
        ? null
        : fbBuilder.writeList(
            _jumpLabels!.map((b) => b.getOrCreateOffset(fbBuilder)).toList(),
          );
    final int? varNamesOffset = _varNames?.getOrCreateOffset(fbBuilder);
    final int? scatterTablesOffset = _scatterTables == null
        ? null
        : fbBuilder.writeList(
            _scatterTables!.map((b) => b.getOrCreateOffset(fbBuilder)).toList(),
          );
    final int? forSequenceOperandsOffset = _forSequenceOperands == null
        ? null
        : fbBuilder.writeList(
            _forSequenceOperands!
                .map((b) => b.getOrCreateOffset(fbBuilder))
                .toList(),
          );
    final int? forRangeOperandsOffset = _forRangeOperands == null
        ? null
        : fbBuilder.writeList(
            _forRangeOperands!
                .map((b) => b.getOrCreateOffset(fbBuilder))
                .toList(),
          );
    final int? rangeComprehensionsOffset = _rangeComprehensions == null
        ? null
        : fbBuilder.writeList(
            _rangeComprehensions!
                .map((b) => b.getOrCreateOffset(fbBuilder))
                .toList(),
          );
    final int? listComprehensionsOffset = _listComprehensions == null
        ? null
        : fbBuilder.writeList(
            _listComprehensions!
                .map((b) => b.getOrCreateOffset(fbBuilder))
                .toList(),
          );
    final int? errorOperandsFullOffset = _errorOperandsFull == null
        ? null
        : fbBuilder.writeList(
            _errorOperandsFull!
                .map((b) => b.getOrCreateOffset(fbBuilder))
                .toList(),
          );
    final int? lambdaProgramsOffset = _lambdaPrograms == null
        ? null
        : fbBuilder.writeList(
            _lambdaPrograms!
                .map((b) => b.getOrCreateOffset(fbBuilder))
                .toList(),
          );
    final int? lineNumberSpansOffset = _lineNumberSpans == null
        ? null
        : fbBuilder.writeList(
            _lineNumberSpans!
                .map((b) => b.getOrCreateOffset(fbBuilder))
                .toList(),
          );
    final int? forkLineNumberSpansOffset = _forkLineNumberSpans == null
        ? null
        : fbBuilder.writeList(
            _forkLineNumberSpans!
                .map((b) => b.getOrCreateOffset(fbBuilder))
                .toList(),
          );
    fbBuilder.startTable(16);
    fbBuilder.addUint16(0, _version);
    fbBuilder.addUint64(1, _builtinSignature);
    fbBuilder.addOffset(2, mainVectorOffset);
    fbBuilder.addOffset(3, forkVectorsOffset);
    fbBuilder.addOffset(4, literalsOffset);
    fbBuilder.addOffset(5, jumpLabelsOffset);
    fbBuilder.addOffset(6, varNamesOffset);
    fbBuilder.addOffset(7, scatterTablesOffset);
    fbBuilder.addOffset(8, forSequenceOperandsOffset);
    fbBuilder.addOffset(9, forRangeOperandsOffset);
    fbBuilder.addOffset(10, rangeComprehensionsOffset);
    fbBuilder.addOffset(11, listComprehensionsOffset);
    fbBuilder.addOffset(12, errorOperandsFullOffset);
    fbBuilder.addOffset(13, lambdaProgramsOffset);
    fbBuilder.addOffset(14, lineNumberSpansOffset);
    fbBuilder.addOffset(15, forkLineNumberSpansOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class StoredProgram {
  StoredProgram._(this._bc, this._bcOffset);
  factory StoredProgram(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<StoredProgram> reader = _StoredProgramReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  StoredProgramLanguageTypeId? get languageType =>
      StoredProgramLanguageTypeId._createOrNull(
        const fb.Uint8Reader().vTableGetNullable(_bc, _bcOffset, 4),
      );
  dynamic get language {
    switch (languageType?.value) {
      case 1:
        return StoredMooRprogram.reader.vTableGetNullable(_bc, _bcOffset, 6);
      default:
        return null;
    }
  }

  @override
  String toString() {
    return 'StoredProgram{languageType: ${languageType}, language: ${language}}';
  }
}

class _StoredProgramReader extends fb.TableReader<StoredProgram> {
  const _StoredProgramReader();

  @override
  StoredProgram createObject(fb.BufferContext bc, int offset) =>
      StoredProgram._(bc, offset);
}

class StoredProgramBuilder {
  StoredProgramBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(2);
  }

  int addLanguageType(StoredProgramLanguageTypeId? languageType) {
    fbBuilder.addUint8(0, languageType?.value);
    return fbBuilder.offset;
  }

  int addLanguageOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class StoredProgramObjectBuilder extends fb.ObjectBuilder {
  final StoredProgramLanguageTypeId? _languageType;
  final dynamic _language;

  StoredProgramObjectBuilder({
    StoredProgramLanguageTypeId? languageType,
    dynamic language,
  }) : _languageType = languageType,
       _language = language;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? languageOffset = _language?.getOrCreateOffset(fbBuilder);
    fbBuilder.startTable(2);
    fbBuilder.addUint8(0, _languageType?.value);
    fbBuilder.addOffset(1, languageOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class LineSpan {
  LineSpan._(this._bc, this._bcOffset);
  factory LineSpan(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<LineSpan> reader = _LineSpanReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get offset => const fb.Uint64Reader().vTableGet(_bc, _bcOffset, 4, 0);
  int get lineNumber => const fb.Uint64Reader().vTableGet(_bc, _bcOffset, 6, 0);

  @override
  String toString() {
    return 'LineSpan{offset: ${offset}, lineNumber: ${lineNumber}}';
  }
}

class _LineSpanReader extends fb.TableReader<LineSpan> {
  const _LineSpanReader();

  @override
  LineSpan createObject(fb.BufferContext bc, int offset) =>
      LineSpan._(bc, offset);
}

class LineSpanBuilder {
  LineSpanBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(2);
  }

  int addOffset(int? offset) {
    fbBuilder.addUint64(0, offset);
    return fbBuilder.offset;
  }

  int addLineNumber(int? lineNumber) {
    fbBuilder.addUint64(1, lineNumber);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class LineSpanObjectBuilder extends fb.ObjectBuilder {
  final int? _offset;
  final int? _lineNumber;

  LineSpanObjectBuilder({
    int? offset,
    int? lineNumber,
  }) : _offset = offset,
       _lineNumber = lineNumber;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    fbBuilder.startTable(2);
    fbBuilder.addUint64(0, _offset);
    fbBuilder.addUint64(1, _lineNumber);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class ForkLineSpans {
  ForkLineSpans._(this._bc, this._bcOffset);
  factory ForkLineSpans(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<ForkLineSpans> reader = _ForkLineSpansReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  List<LineSpan>? get spans => const fb.ListReader<LineSpan>(
    LineSpan.reader,
  ).vTableGetNullable(_bc, _bcOffset, 4);

  @override
  String toString() {
    return 'ForkLineSpans{spans: ${spans}}';
  }
}

class _ForkLineSpansReader extends fb.TableReader<ForkLineSpans> {
  const _ForkLineSpansReader();

  @override
  ForkLineSpans createObject(fb.BufferContext bc, int offset) =>
      ForkLineSpans._(bc, offset);
}

class ForkLineSpansBuilder {
  ForkLineSpansBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(1);
  }

  int addSpansOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class ForkLineSpansObjectBuilder extends fb.ObjectBuilder {
  final List<LineSpanObjectBuilder>? _spans;

  ForkLineSpansObjectBuilder({
    List<LineSpanObjectBuilder>? spans,
  }) : _spans = spans;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? spansOffset = _spans == null
        ? null
        : fbBuilder.writeList(
            _spans!.map((b) => b.getOrCreateOffset(fbBuilder)).toList(),
          );
    fbBuilder.startTable(1);
    fbBuilder.addOffset(0, spansOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
