// automatically generated by the FlatBuffers compiler, do not modify
// ignore_for_file: unused_import, unused_field, unused_element, unused_local_variable

library moor_var;

import 'dart:typed_data' show Uint8List;
import 'package:flat_buffers/flat_buffers.dart' as fb;

import './moor_rpc_moor_common_generated.dart' as moor_common;
import './moor_rpc_moor_program_generated.dart' as moor_program;
import './moor_rpc_moor_rpc_generated.dart' as moor_rpc;

class VarUnionTypeId {
  final int value;
  const VarUnionTypeId._(this.value);

  factory VarUnionTypeId.fromValue(int value) {
    final result = values[value];
    if (result == null) {
      throw StateError('Invalid value $value for bit flag enum VarUnionTypeId');
    }
    return result;
  }

  static VarUnionTypeId? _createOrNull(int? value) =>
      value == null ? null : VarUnionTypeId.fromValue(value);

  static const int minValue = 0;
  static const int maxValue = 14;
  static bool containsValue(int value) => values.containsKey(value);

  static const VarUnionTypeId NONE = VarUnionTypeId._(0);
  static const VarUnionTypeId VarNone = VarUnionTypeId._(1);
  static const VarUnionTypeId VarBool = VarUnionTypeId._(2);
  static const VarUnionTypeId VarInt = VarUnionTypeId._(3);
  static const VarUnionTypeId VarFloat = VarUnionTypeId._(4);
  static const VarUnionTypeId VarStr = VarUnionTypeId._(5);
  static const VarUnionTypeId VarObj = VarUnionTypeId._(6);
  static const VarUnionTypeId VarErr = VarUnionTypeId._(7);
  static const VarUnionTypeId VarList = VarUnionTypeId._(8);
  static const VarUnionTypeId VarMap = VarUnionTypeId._(9);
  static const VarUnionTypeId VarSym = VarUnionTypeId._(10);
  static const VarUnionTypeId VarBinary = VarUnionTypeId._(11);
  static const VarUnionTypeId VarFlyweight = VarUnionTypeId._(12);
  static const VarUnionTypeId VarLambda = VarUnionTypeId._(13);
  static const VarUnionTypeId VarAnonymous = VarUnionTypeId._(14);
  static const Map<int, VarUnionTypeId> values = {
    0: NONE,
    1: VarNone,
    2: VarBool,
    3: VarInt,
    4: VarFloat,
    5: VarStr,
    6: VarObj,
    7: VarErr,
    8: VarList,
    9: VarMap,
    10: VarSym,
    11: VarBinary,
    12: VarFlyweight,
    13: VarLambda,
    14: VarAnonymous,
  };

  static const fb.Reader<VarUnionTypeId> reader = _VarUnionTypeIdReader();

  @override
  String toString() {
    return 'VarUnionTypeId{value: $value}';
  }
}

class _VarUnionTypeIdReader extends fb.Reader<VarUnionTypeId> {
  const _VarUnionTypeIdReader();

  @override
  int get size => 1;

  @override
  VarUnionTypeId read(fb.BufferContext bc, int offset) =>
      VarUnionTypeId.fromValue(const fb.Uint8Reader().read(bc, offset));
}

class VarNone {
  VarNone._(this._bc, this._bcOffset);
  factory VarNone(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<VarNone> reader = _VarNoneReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  @override
  String toString() {
    return 'VarNone{}';
  }
}

class _VarNoneReader extends fb.TableReader<VarNone> {
  const _VarNoneReader();

  @override
  VarNone createObject(fb.BufferContext bc, int offset) =>
      VarNone._(bc, offset);
}

class VarNoneObjectBuilder extends fb.ObjectBuilder {
  VarNoneObjectBuilder();

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    fbBuilder.startTable(0);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class VarBool {
  VarBool._(this._bc, this._bcOffset);
  factory VarBool(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<VarBool> reader = _VarBoolReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  bool get value => const fb.BoolReader().vTableGet(_bc, _bcOffset, 4, false);

  @override
  String toString() {
    return 'VarBool{value: ${value}}';
  }
}

class _VarBoolReader extends fb.TableReader<VarBool> {
  const _VarBoolReader();

  @override
  VarBool createObject(fb.BufferContext bc, int offset) =>
      VarBool._(bc, offset);
}

class VarBoolBuilder {
  VarBoolBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(1);
  }

  int addValue(bool? value) {
    fbBuilder.addBool(0, value);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class VarBoolObjectBuilder extends fb.ObjectBuilder {
  final bool? _value;

  VarBoolObjectBuilder({
    bool? value,
  }) : _value = value;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    fbBuilder.startTable(1);
    fbBuilder.addBool(0, _value);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class VarInt {
  VarInt._(this._bc, this._bcOffset);
  factory VarInt(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<VarInt> reader = _VarIntReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  int get value => const fb.Int64Reader().vTableGet(_bc, _bcOffset, 4, 0);

  @override
  String toString() {
    return 'VarInt{value: ${value}}';
  }
}

class _VarIntReader extends fb.TableReader<VarInt> {
  const _VarIntReader();

  @override
  VarInt createObject(fb.BufferContext bc, int offset) => VarInt._(bc, offset);
}

class VarIntBuilder {
  VarIntBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(1);
  }

  int addValue(int? value) {
    fbBuilder.addInt64(0, value);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class VarIntObjectBuilder extends fb.ObjectBuilder {
  final int? _value;

  VarIntObjectBuilder({
    int? value,
  }) : _value = value;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    fbBuilder.startTable(1);
    fbBuilder.addInt64(0, _value);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class VarFloat {
  VarFloat._(this._bc, this._bcOffset);
  factory VarFloat(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<VarFloat> reader = _VarFloatReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  double get value =>
      const fb.Float64Reader().vTableGet(_bc, _bcOffset, 4, 0.0);

  @override
  String toString() {
    return 'VarFloat{value: ${value}}';
  }
}

class _VarFloatReader extends fb.TableReader<VarFloat> {
  const _VarFloatReader();

  @override
  VarFloat createObject(fb.BufferContext bc, int offset) =>
      VarFloat._(bc, offset);
}

class VarFloatBuilder {
  VarFloatBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(1);
  }

  int addValue(double? value) {
    fbBuilder.addFloat64(0, value);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class VarFloatObjectBuilder extends fb.ObjectBuilder {
  final double? _value;

  VarFloatObjectBuilder({
    double? value,
  }) : _value = value;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    fbBuilder.startTable(1);
    fbBuilder.addFloat64(0, _value);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class VarStr {
  VarStr._(this._bc, this._bcOffset);
  factory VarStr(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<VarStr> reader = _VarStrReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  String? get value =>
      const fb.StringReader().vTableGetNullable(_bc, _bcOffset, 4);

  @override
  String toString() {
    return 'VarStr{value: ${value}}';
  }
}

class _VarStrReader extends fb.TableReader<VarStr> {
  const _VarStrReader();

  @override
  VarStr createObject(fb.BufferContext bc, int offset) => VarStr._(bc, offset);
}

class VarStrBuilder {
  VarStrBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(1);
  }

  int addValueOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class VarStrObjectBuilder extends fb.ObjectBuilder {
  final String? _value;

  VarStrObjectBuilder({
    String? value,
  }) : _value = value;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? valueOffset = _value == null
        ? null
        : fbBuilder.writeString(_value!);
    fbBuilder.startTable(1);
    fbBuilder.addOffset(0, valueOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class VarObj {
  VarObj._(this._bc, this._bcOffset);
  factory VarObj(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<VarObj> reader = _VarObjReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  moor_common.Obj? get obj =>
      moor_common.Obj.reader.vTableGetNullable(_bc, _bcOffset, 4);

  @override
  String toString() {
    return 'VarObj{obj: ${obj}}';
  }
}

class _VarObjReader extends fb.TableReader<VarObj> {
  const _VarObjReader();

  @override
  VarObj createObject(fb.BufferContext bc, int offset) => VarObj._(bc, offset);
}

class VarObjBuilder {
  VarObjBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(1);
  }

  int addObjOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class VarObjObjectBuilder extends fb.ObjectBuilder {
  final moor_common.ObjObjectBuilder? _obj;

  VarObjObjectBuilder({
    moor_common.ObjObjectBuilder? obj,
  }) : _obj = obj;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? objOffset = _obj?.getOrCreateOffset(fbBuilder);
    fbBuilder.startTable(1);
    fbBuilder.addOffset(0, objOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class VarErr {
  VarErr._(this._bc, this._bcOffset);
  factory VarErr(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<VarErr> reader = _VarErrReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  moor_common.Error? get error =>
      moor_common.Error.reader.vTableGetNullable(_bc, _bcOffset, 4);

  @override
  String toString() {
    return 'VarErr{error: ${error}}';
  }
}

class _VarErrReader extends fb.TableReader<VarErr> {
  const _VarErrReader();

  @override
  VarErr createObject(fb.BufferContext bc, int offset) => VarErr._(bc, offset);
}

class VarErrBuilder {
  VarErrBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(1);
  }

  int addErrorOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class VarErrObjectBuilder extends fb.ObjectBuilder {
  final moor_common.ErrorObjectBuilder? _error;

  VarErrObjectBuilder({
    moor_common.ErrorObjectBuilder? error,
  }) : _error = error;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? errorOffset = _error?.getOrCreateOffset(fbBuilder);
    fbBuilder.startTable(1);
    fbBuilder.addOffset(0, errorOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class VarSym {
  VarSym._(this._bc, this._bcOffset);
  factory VarSym(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<VarSym> reader = _VarSymReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  moor_common.Symbol? get symbol =>
      moor_common.Symbol.reader.vTableGetNullable(_bc, _bcOffset, 4);

  @override
  String toString() {
    return 'VarSym{symbol: ${symbol}}';
  }
}

class _VarSymReader extends fb.TableReader<VarSym> {
  const _VarSymReader();

  @override
  VarSym createObject(fb.BufferContext bc, int offset) => VarSym._(bc, offset);
}

class VarSymBuilder {
  VarSymBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(1);
  }

  int addSymbolOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class VarSymObjectBuilder extends fb.ObjectBuilder {
  final moor_common.SymbolObjectBuilder? _symbol;

  VarSymObjectBuilder({
    moor_common.SymbolObjectBuilder? symbol,
  }) : _symbol = symbol;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? symbolOffset = _symbol?.getOrCreateOffset(fbBuilder);
    fbBuilder.startTable(1);
    fbBuilder.addOffset(0, symbolOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class VarBinary {
  VarBinary._(this._bc, this._bcOffset);
  factory VarBinary(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<VarBinary> reader = _VarBinaryReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  List<int>? get data =>
      const fb.Uint8ListReader().vTableGetNullable(_bc, _bcOffset, 4);

  @override
  String toString() {
    return 'VarBinary{data: ${data}}';
  }
}

class _VarBinaryReader extends fb.TableReader<VarBinary> {
  const _VarBinaryReader();

  @override
  VarBinary createObject(fb.BufferContext bc, int offset) =>
      VarBinary._(bc, offset);
}

class VarBinaryBuilder {
  VarBinaryBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(1);
  }

  int addDataOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class VarBinaryObjectBuilder extends fb.ObjectBuilder {
  final List<int>? _data;

  VarBinaryObjectBuilder({
    List<int>? data,
  }) : _data = data;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? dataOffset = _data == null
        ? null
        : fbBuilder.writeListUint8(_data!);
    fbBuilder.startTable(1);
    fbBuilder.addOffset(0, dataOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class VarList {
  VarList._(this._bc, this._bcOffset);
  factory VarList(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<VarList> reader = _VarListReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  List<Var>? get elements =>
      const fb.ListReader<Var>(Var.reader).vTableGetNullable(_bc, _bcOffset, 4);

  @override
  String toString() {
    return 'VarList{elements: ${elements}}';
  }
}

class _VarListReader extends fb.TableReader<VarList> {
  const _VarListReader();

  @override
  VarList createObject(fb.BufferContext bc, int offset) =>
      VarList._(bc, offset);
}

class VarListBuilder {
  VarListBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(1);
  }

  int addElementsOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class VarListObjectBuilder extends fb.ObjectBuilder {
  final List<VarObjectBuilder>? _elements;

  VarListObjectBuilder({
    List<VarObjectBuilder>? elements,
  }) : _elements = elements;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? elementsOffset = _elements == null
        ? null
        : fbBuilder.writeList(
            _elements!.map((b) => b.getOrCreateOffset(fbBuilder)).toList(),
          );
    fbBuilder.startTable(1);
    fbBuilder.addOffset(0, elementsOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class VarMapPair {
  VarMapPair._(this._bc, this._bcOffset);
  factory VarMapPair(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<VarMapPair> reader = _VarMapPairReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  Var? get key => Var.reader.vTableGetNullable(_bc, _bcOffset, 4);
  Var? get value => Var.reader.vTableGetNullable(_bc, _bcOffset, 6);

  @override
  String toString() {
    return 'VarMapPair{key: ${key}, value: ${value}}';
  }
}

class _VarMapPairReader extends fb.TableReader<VarMapPair> {
  const _VarMapPairReader();

  @override
  VarMapPair createObject(fb.BufferContext bc, int offset) =>
      VarMapPair._(bc, offset);
}

class VarMapPairBuilder {
  VarMapPairBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(2);
  }

  int addKeyOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }

  int addValueOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class VarMapPairObjectBuilder extends fb.ObjectBuilder {
  final VarObjectBuilder? _key;
  final VarObjectBuilder? _value;

  VarMapPairObjectBuilder({
    VarObjectBuilder? key,
    VarObjectBuilder? value,
  }) : _key = key,
       _value = value;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? keyOffset = _key?.getOrCreateOffset(fbBuilder);
    final int? valueOffset = _value?.getOrCreateOffset(fbBuilder);
    fbBuilder.startTable(2);
    fbBuilder.addOffset(0, keyOffset);
    fbBuilder.addOffset(1, valueOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class VarMap {
  VarMap._(this._bc, this._bcOffset);
  factory VarMap(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<VarMap> reader = _VarMapReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  List<VarMapPair>? get pairs => const fb.ListReader<VarMapPair>(
    VarMapPair.reader,
  ).vTableGetNullable(_bc, _bcOffset, 4);

  @override
  String toString() {
    return 'VarMap{pairs: ${pairs}}';
  }
}

class _VarMapReader extends fb.TableReader<VarMap> {
  const _VarMapReader();

  @override
  VarMap createObject(fb.BufferContext bc, int offset) => VarMap._(bc, offset);
}

class VarMapBuilder {
  VarMapBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(1);
  }

  int addPairsOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class VarMapObjectBuilder extends fb.ObjectBuilder {
  final List<VarMapPairObjectBuilder>? _pairs;

  VarMapObjectBuilder({
    List<VarMapPairObjectBuilder>? pairs,
  }) : _pairs = pairs;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? pairsOffset = _pairs == null
        ? null
        : fbBuilder.writeList(
            _pairs!.map((b) => b.getOrCreateOffset(fbBuilder)).toList(),
          );
    fbBuilder.startTable(1);
    fbBuilder.addOffset(0, pairsOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class FlyweightSlot {
  FlyweightSlot._(this._bc, this._bcOffset);
  factory FlyweightSlot(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<FlyweightSlot> reader = _FlyweightSlotReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  moor_common.Symbol? get name =>
      moor_common.Symbol.reader.vTableGetNullable(_bc, _bcOffset, 4);
  Var? get value => Var.reader.vTableGetNullable(_bc, _bcOffset, 6);

  @override
  String toString() {
    return 'FlyweightSlot{name: ${name}, value: ${value}}';
  }
}

class _FlyweightSlotReader extends fb.TableReader<FlyweightSlot> {
  const _FlyweightSlotReader();

  @override
  FlyweightSlot createObject(fb.BufferContext bc, int offset) =>
      FlyweightSlot._(bc, offset);
}

class FlyweightSlotBuilder {
  FlyweightSlotBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(2);
  }

  int addNameOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }

  int addValueOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class FlyweightSlotObjectBuilder extends fb.ObjectBuilder {
  final moor_common.SymbolObjectBuilder? _name;
  final VarObjectBuilder? _value;

  FlyweightSlotObjectBuilder({
    moor_common.SymbolObjectBuilder? name,
    VarObjectBuilder? value,
  }) : _name = name,
       _value = value;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? nameOffset = _name?.getOrCreateOffset(fbBuilder);
    final int? valueOffset = _value?.getOrCreateOffset(fbBuilder);
    fbBuilder.startTable(2);
    fbBuilder.addOffset(0, nameOffset);
    fbBuilder.addOffset(1, valueOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class VarFlyweight {
  VarFlyweight._(this._bc, this._bcOffset);
  factory VarFlyweight(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<VarFlyweight> reader = _VarFlyweightReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  moor_common.Obj? get delegate =>
      moor_common.Obj.reader.vTableGetNullable(_bc, _bcOffset, 4);
  List<FlyweightSlot>? get slots => const fb.ListReader<FlyweightSlot>(
    FlyweightSlot.reader,
  ).vTableGetNullable(_bc, _bcOffset, 6);
  VarList? get contents => VarList.reader.vTableGetNullable(_bc, _bcOffset, 8);

  @override
  String toString() {
    return 'VarFlyweight{delegate: ${delegate}, slots: ${slots}, contents: ${contents}}';
  }
}

class _VarFlyweightReader extends fb.TableReader<VarFlyweight> {
  const _VarFlyweightReader();

  @override
  VarFlyweight createObject(fb.BufferContext bc, int offset) =>
      VarFlyweight._(bc, offset);
}

class VarFlyweightBuilder {
  VarFlyweightBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(3);
  }

  int addDelegateOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }

  int addSlotsOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }

  int addContentsOffset(int? offset) {
    fbBuilder.addOffset(2, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class VarFlyweightObjectBuilder extends fb.ObjectBuilder {
  final moor_common.ObjObjectBuilder? _delegate;
  final List<FlyweightSlotObjectBuilder>? _slots;
  final VarListObjectBuilder? _contents;

  VarFlyweightObjectBuilder({
    moor_common.ObjObjectBuilder? delegate,
    List<FlyweightSlotObjectBuilder>? slots,
    VarListObjectBuilder? contents,
  }) : _delegate = delegate,
       _slots = slots,
       _contents = contents;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? delegateOffset = _delegate?.getOrCreateOffset(fbBuilder);
    final int? slotsOffset = _slots == null
        ? null
        : fbBuilder.writeList(
            _slots!.map((b) => b.getOrCreateOffset(fbBuilder)).toList(),
          );
    final int? contentsOffset = _contents?.getOrCreateOffset(fbBuilder);
    fbBuilder.startTable(3);
    fbBuilder.addOffset(0, delegateOffset);
    fbBuilder.addOffset(1, slotsOffset);
    fbBuilder.addOffset(2, contentsOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class VarLambda {
  VarLambda._(this._bc, this._bcOffset);
  factory VarLambda(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<VarLambda> reader = _VarLambdaReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  moor_program.StoredScatterArgs? get params => moor_program
      .StoredScatterArgs
      .reader
      .vTableGetNullable(_bc, _bcOffset, 4);
  moor_program.StoredProgram? get body =>
      moor_program.StoredProgram.reader.vTableGetNullable(_bc, _bcOffset, 6);
  List<VarList>? get capturedEnv => const fb.ListReader<VarList>(
    VarList.reader,
  ).vTableGetNullable(_bc, _bcOffset, 8);
  moor_program.StoredName? get selfVar =>
      moor_program.StoredName.reader.vTableGetNullable(_bc, _bcOffset, 10);

  @override
  String toString() {
    return 'VarLambda{params: ${params}, body: ${body}, capturedEnv: ${capturedEnv}, selfVar: ${selfVar}}';
  }
}

class _VarLambdaReader extends fb.TableReader<VarLambda> {
  const _VarLambdaReader();

  @override
  VarLambda createObject(fb.BufferContext bc, int offset) =>
      VarLambda._(bc, offset);
}

class VarLambdaBuilder {
  VarLambdaBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(4);
  }

  int addParamsOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }

  int addBodyOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }

  int addCapturedEnvOffset(int? offset) {
    fbBuilder.addOffset(2, offset);
    return fbBuilder.offset;
  }

  int addSelfVarOffset(int? offset) {
    fbBuilder.addOffset(3, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class VarLambdaObjectBuilder extends fb.ObjectBuilder {
  final moor_program.StoredScatterArgsObjectBuilder? _params;
  final moor_program.StoredProgramObjectBuilder? _body;
  final List<VarListObjectBuilder>? _capturedEnv;
  final moor_program.StoredNameObjectBuilder? _selfVar;

  VarLambdaObjectBuilder({
    moor_program.StoredScatterArgsObjectBuilder? params,
    moor_program.StoredProgramObjectBuilder? body,
    List<VarListObjectBuilder>? capturedEnv,
    moor_program.StoredNameObjectBuilder? selfVar,
  }) : _params = params,
       _body = body,
       _capturedEnv = capturedEnv,
       _selfVar = selfVar;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? paramsOffset = _params?.getOrCreateOffset(fbBuilder);
    final int? bodyOffset = _body?.getOrCreateOffset(fbBuilder);
    final int? capturedEnvOffset = _capturedEnv == null
        ? null
        : fbBuilder.writeList(
            _capturedEnv!.map((b) => b.getOrCreateOffset(fbBuilder)).toList(),
          );
    final int? selfVarOffset = _selfVar?.getOrCreateOffset(fbBuilder);
    fbBuilder.startTable(4);
    fbBuilder.addOffset(0, paramsOffset);
    fbBuilder.addOffset(1, bodyOffset);
    fbBuilder.addOffset(2, capturedEnvOffset);
    fbBuilder.addOffset(3, selfVarOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class VarAnonymous {
  VarAnonymous._(this._bc, this._bcOffset);
  factory VarAnonymous(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<VarAnonymous> reader = _VarAnonymousReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  moor_common.Obj? get obj =>
      moor_common.Obj.reader.vTableGetNullable(_bc, _bcOffset, 4);

  @override
  String toString() {
    return 'VarAnonymous{obj: ${obj}}';
  }
}

class _VarAnonymousReader extends fb.TableReader<VarAnonymous> {
  const _VarAnonymousReader();

  @override
  VarAnonymous createObject(fb.BufferContext bc, int offset) =>
      VarAnonymous._(bc, offset);
}

class VarAnonymousBuilder {
  VarAnonymousBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(1);
  }

  int addObjOffset(int? offset) {
    fbBuilder.addOffset(0, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class VarAnonymousObjectBuilder extends fb.ObjectBuilder {
  final moor_common.ObjObjectBuilder? _obj;

  VarAnonymousObjectBuilder({
    moor_common.ObjObjectBuilder? obj,
  }) : _obj = obj;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? objOffset = _obj?.getOrCreateOffset(fbBuilder);
    fbBuilder.startTable(1);
    fbBuilder.addOffset(0, objOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}

class Var {
  Var._(this._bc, this._bcOffset);
  factory Var(List<int> bytes) {
    final rootRef = fb.BufferContext.fromBytes(bytes);
    return reader.read(rootRef, 0);
  }

  static const fb.Reader<Var> reader = _VarReader();

  final fb.BufferContext _bc;
  final int _bcOffset;

  VarUnionTypeId? get variantType => VarUnionTypeId._createOrNull(
    const fb.Uint8Reader().vTableGetNullable(_bc, _bcOffset, 4),
  );
  dynamic get variant {
    switch (variantType?.value) {
      case 1:
        return VarNone.reader.vTableGetNullable(_bc, _bcOffset, 6);
      case 2:
        return VarBool.reader.vTableGetNullable(_bc, _bcOffset, 6);
      case 3:
        return VarInt.reader.vTableGetNullable(_bc, _bcOffset, 6);
      case 4:
        return VarFloat.reader.vTableGetNullable(_bc, _bcOffset, 6);
      case 5:
        return VarStr.reader.vTableGetNullable(_bc, _bcOffset, 6);
      case 6:
        return VarObj.reader.vTableGetNullable(_bc, _bcOffset, 6);
      case 7:
        return VarErr.reader.vTableGetNullable(_bc, _bcOffset, 6);
      case 8:
        return VarList.reader.vTableGetNullable(_bc, _bcOffset, 6);
      case 9:
        return VarMap.reader.vTableGetNullable(_bc, _bcOffset, 6);
      case 10:
        return VarSym.reader.vTableGetNullable(_bc, _bcOffset, 6);
      case 11:
        return VarBinary.reader.vTableGetNullable(_bc, _bcOffset, 6);
      case 12:
        return VarFlyweight.reader.vTableGetNullable(_bc, _bcOffset, 6);
      case 13:
        return VarLambda.reader.vTableGetNullable(_bc, _bcOffset, 6);
      case 14:
        return VarAnonymous.reader.vTableGetNullable(_bc, _bcOffset, 6);
      default:
        return null;
    }
  }

  @override
  String toString() {
    return 'Var{variantType: ${variantType}, variant: ${variant}}';
  }
}

class _VarReader extends fb.TableReader<Var> {
  const _VarReader();

  @override
  Var createObject(fb.BufferContext bc, int offset) => Var._(bc, offset);
}

class VarBuilder {
  VarBuilder(this.fbBuilder);

  final fb.Builder fbBuilder;

  void begin() {
    fbBuilder.startTable(2);
  }

  int addVariantType(VarUnionTypeId? variantType) {
    fbBuilder.addUint8(0, variantType?.value);
    return fbBuilder.offset;
  }

  int addVariantOffset(int? offset) {
    fbBuilder.addOffset(1, offset);
    return fbBuilder.offset;
  }

  int finish() {
    return fbBuilder.endTable();
  }
}

class VarObjectBuilder extends fb.ObjectBuilder {
  final VarUnionTypeId? _variantType;
  final dynamic _variant;

  VarObjectBuilder({
    VarUnionTypeId? variantType,
    dynamic variant,
  }) : _variantType = variantType,
       _variant = variant;

  /// Finish building, and store into the [fbBuilder].
  @override
  int finish(fb.Builder fbBuilder) {
    final int? variantOffset = _variant?.getOrCreateOffset(fbBuilder);
    fbBuilder.startTable(2);
    fbBuilder.addUint8(0, _variantType?.value);
    fbBuilder.addOffset(1, variantOffset);
    return fbBuilder.endTable();
  }

  /// Convenience method to serialize to byte list.
  @override
  Uint8List toBytes([String? fileIdentifier]) {
    final fbBuilder = fb.Builder(deduplicateTables: false);
    fbBuilder.finish(finish(fbBuilder), fileIdentifier);
    return fbBuilder.buffer;
  }
}
