# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorCommon

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class AssignmentToCapturedVariable(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AssignmentToCapturedVariable()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAssignmentToCapturedVariable(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # AssignmentToCapturedVariable
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AssignmentToCapturedVariable
    def Context(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.CompileContext import CompileContext
            obj = CompileContext()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # AssignmentToCapturedVariable
    def VarName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.Symbol import Symbol
            obj = Symbol()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def AssignmentToCapturedVariableStart(builder): builder.StartObject(2)
def Start(builder):
    return AssignmentToCapturedVariableStart(builder)
def AssignmentToCapturedVariableAddContext(builder, context): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(context), 0)
def AddContext(builder, context):
    return AssignmentToCapturedVariableAddContext(builder, context)
def AssignmentToCapturedVariableAddVarName(builder, varName): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(varName), 0)
def AddVarName(builder, varName):
    return AssignmentToCapturedVariableAddVarName(builder, varName)
def AssignmentToCapturedVariableEnd(builder): return builder.EndObject()
def End(builder):
    return AssignmentToCapturedVariableEnd(builder)