# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorCommon

class EventUnion(object):
    NONE = 0
    NotifyEvent = 1
    PresentEvent = 2
    UnpresentEvent = 3
    TracebackEvent = 4
    DataEvent = 5
