[workspace]

[package]
name = "snore-session-runner"
version = "0.1.0"
edition = "2024"

[dependencies]
eyre = "0.6"
flume = "0.12"
moor-common = { path = "../../../../crates/common" }
moor-db = { path = "../../../../crates/db" }
moor-kernel = { path = "../../../../crates/kernel" }
moor-moot = { path = "../../../../crates/testing/moot" }
moor-objdef = { path = "../../../../crates/objdef" }
moor-var = { path = "../../../../crates/var" }
semver = "1"
uuid = "1.23"
