# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class BatchWorldStateReply(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BatchWorldStateReply()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBatchWorldStateReply(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # BatchWorldStateReply
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BatchWorldStateReply
    def Results(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from MoorRpc.WorldStateResultEntry import WorldStateResultEntry
            obj = WorldStateResultEntry()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # BatchWorldStateReply
    def ResultsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # BatchWorldStateReply
    def ResultsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def BatchWorldStateReplyStart(builder): builder.StartObject(1)
def Start(builder):
    return BatchWorldStateReplyStart(builder)
def BatchWorldStateReplyAddResults(builder, results): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(results), 0)
def AddResults(builder, results):
    return BatchWorldStateReplyAddResults(builder, results)
def BatchWorldStateReplyStartResultsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartResultsVector(builder, numElems):
    return BatchWorldStateReplyStartResultsVector(builder, numElems)
def BatchWorldStateReplyEnd(builder): return builder.EndObject()
def End(builder):
    return BatchWorldStateReplyEnd(builder)