# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class BatchWorldState(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BatchWorldState()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBatchWorldState(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # BatchWorldState
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BatchWorldState
    def AuthToken(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorRpc.AuthToken import AuthToken
            obj = AuthToken()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # BatchWorldState
    def Actions(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from MoorRpc.WorldStateActionEntry import WorldStateActionEntry
            obj = WorldStateActionEntry()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # BatchWorldState
    def ActionsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # BatchWorldState
    def ActionsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # BatchWorldState
    def Rollback(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def BatchWorldStateStart(builder): builder.StartObject(3)
def Start(builder):
    return BatchWorldStateStart(builder)
def BatchWorldStateAddAuthToken(builder, authToken): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(authToken), 0)
def AddAuthToken(builder, authToken):
    return BatchWorldStateAddAuthToken(builder, authToken)
def BatchWorldStateAddActions(builder, actions): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(actions), 0)
def AddActions(builder, actions):
    return BatchWorldStateAddActions(builder, actions)
def BatchWorldStateStartActionsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartActionsVector(builder, numElems):
    return BatchWorldStateStartActionsVector(builder, numElems)
def BatchWorldStateAddRollback(builder, rollback): builder.PrependBoolSlot(2, rollback, 0)
def AddRollback(builder, rollback):
    return BatchWorldStateAddRollback(builder, rollback)
def BatchWorldStateEnd(builder): return builder.EndObject()
def End(builder):
    return BatchWorldStateEnd(builder)