# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CaptureOutputInvocation(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CaptureOutputInvocation()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCaptureOutputInvocation(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CaptureOutputInvocation
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CaptureOutputInvocation
    def TimeoutMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 60000

def CaptureOutputInvocationStart(builder): builder.StartObject(1)
def Start(builder):
    return CaptureOutputInvocationStart(builder)
def CaptureOutputInvocationAddTimeoutMs(builder, timeoutMs): builder.PrependUint64Slot(0, timeoutMs, 60000)
def AddTimeoutMs(builder, timeoutMs):
    return CaptureOutputInvocationAddTimeoutMs(builder, timeoutMs)
def CaptureOutputInvocationEnd(builder): return builder.EndObject()
def End(builder):
    return CaptureOutputInvocationEnd(builder)