# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ClientEvents(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ClientEvents()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsClientEvents(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ClientEvents
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ClientEvents
    def Events(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from MoorRpc.ClientEvent import ClientEvent
            obj = ClientEvent()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ClientEvents
    def EventsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ClientEvents
    def EventsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # ClientEvents
    def LatestSequence(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def ClientEventsStart(builder): builder.StartObject(2)
def Start(builder):
    return ClientEventsStart(builder)
def ClientEventsAddEvents(builder, events): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(events), 0)
def AddEvents(builder, events):
    return ClientEventsAddEvents(builder, events)
def ClientEventsStartEventsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartEventsVector(builder, numElems):
    return ClientEventsStartEventsVector(builder, numElems)
def ClientEventsAddLatestSequence(builder, latestSequence): builder.PrependUint64Slot(1, latestSequence, 0)
def AddLatestSequence(builder, latestSequence):
    return ClientEventsAddLatestSequence(builder, latestSequence)
def ClientEventsEnd(builder): return builder.EndObject()
def End(builder):
    return ClientEventsEnd(builder)