# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HostBroadcastListen(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HostBroadcastListen()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHostBroadcastListen(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HostBroadcastListen
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HostBroadcastListen
    def HandlerObject(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.Obj import Obj
            obj = Obj()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # HostBroadcastListen
    def HostType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # HostBroadcastListen
    def Port(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # HostBroadcastListen
    def Options(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from MoorVar.VarMapPair import VarMapPair
            obj = VarMapPair()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # HostBroadcastListen
    def OptionsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # HostBroadcastListen
    def OptionsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

def HostBroadcastListenStart(builder): builder.StartObject(4)
def Start(builder):
    return HostBroadcastListenStart(builder)
def HostBroadcastListenAddHandlerObject(builder, handlerObject): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(handlerObject), 0)
def AddHandlerObject(builder, handlerObject):
    return HostBroadcastListenAddHandlerObject(builder, handlerObject)
def HostBroadcastListenAddHostType(builder, hostType): builder.PrependUint8Slot(1, hostType, 0)
def AddHostType(builder, hostType):
    return HostBroadcastListenAddHostType(builder, hostType)
def HostBroadcastListenAddPort(builder, port): builder.PrependUint16Slot(2, port, 0)
def AddPort(builder, port):
    return HostBroadcastListenAddPort(builder, port)
def HostBroadcastListenAddOptions(builder, options): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(options), 0)
def AddOptions(builder, options):
    return HostBroadcastListenAddOptions(builder, options)
def HostBroadcastListenStartOptionsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartOptionsVector(builder, numElems):
    return HostBroadcastListenStartOptionsVector(builder, numElems)
def HostBroadcastListenEnd(builder): return builder.EndObject()
def End(builder):
    return HostBroadcastListenEnd(builder)