# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class InvocationResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = InvocationResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsInvocationResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # InvocationResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # InvocationResponse
    def OutcomeType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # InvocationResponse
    def Outcome(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

    # InvocationResponse
    def Output(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from MoorCommon.NarrativeEvent import NarrativeEvent
            obj = NarrativeEvent()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # InvocationResponse
    def OutputLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # InvocationResponse
    def OutputIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def InvocationResponseStart(builder): builder.StartObject(3)
def Start(builder):
    return InvocationResponseStart(builder)
def InvocationResponseAddOutcomeType(builder, outcomeType): builder.PrependUint8Slot(0, outcomeType, 0)
def AddOutcomeType(builder, outcomeType):
    return InvocationResponseAddOutcomeType(builder, outcomeType)
def InvocationResponseAddOutcome(builder, outcome): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(outcome), 0)
def AddOutcome(builder, outcome):
    return InvocationResponseAddOutcome(builder, outcome)
def InvocationResponseAddOutput(builder, output): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(output), 0)
def AddOutput(builder, output):
    return InvocationResponseAddOutput(builder, output)
def InvocationResponseStartOutputVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartOutputVector(builder, numElems):
    return InvocationResponseStartOutputVector(builder, numElems)
def InvocationResponseEnd(builder): return builder.EndObject()
def End(builder):
    return InvocationResponseEnd(builder)