# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PresentationSnapshot(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PresentationSnapshot()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPresentationSnapshot(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PresentationSnapshot
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PresentationSnapshot
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PresentationSnapshot
    def EncryptedBlob(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # PresentationSnapshot
    def EncryptedBlobAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # PresentationSnapshot
    def EncryptedBlobLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # PresentationSnapshot
    def EncryptedBlobIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def PresentationSnapshotStart(builder): builder.StartObject(2)
def Start(builder):
    return PresentationSnapshotStart(builder)
def PresentationSnapshotAddId(builder, id): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)
def AddId(builder, id):
    return PresentationSnapshotAddId(builder, id)
def PresentationSnapshotAddEncryptedBlob(builder, encryptedBlob): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(encryptedBlob), 0)
def AddEncryptedBlob(builder, encryptedBlob):
    return PresentationSnapshotAddEncryptedBlob(builder, encryptedBlob)
def PresentationSnapshotStartEncryptedBlobVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def StartEncryptedBlobVector(builder, numElems):
    return PresentationSnapshotStartEncryptedBlobVector(builder, numElems)
def PresentationSnapshotEnd(builder): return builder.EndObject()
def End(builder):
    return PresentationSnapshotEnd(builder)