# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ReplayClientEvents(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ReplayClientEvents()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsReplayClientEvents(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ReplayClientEvents
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ReplayClientEvents
    def ClientToken(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorRpc.ClientToken import ClientToken
            obj = ClientToken()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ReplayClientEvents
    def AfterSequence(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # ReplayClientEvents
    def Limit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def ReplayClientEventsStart(builder): builder.StartObject(3)
def Start(builder):
    return ReplayClientEventsStart(builder)
def ReplayClientEventsAddClientToken(builder, clientToken): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(clientToken), 0)
def AddClientToken(builder, clientToken):
    return ReplayClientEventsAddClientToken(builder, clientToken)
def ReplayClientEventsAddAfterSequence(builder, afterSequence): builder.PrependUint64Slot(1, afterSequence, 0)
def AddAfterSequence(builder, afterSequence):
    return ReplayClientEventsAddAfterSequence(builder, afterSequence)
def ReplayClientEventsAddLimit(builder, limit): builder.PrependUint32Slot(2, limit, 0)
def AddLimit(builder, limit):
    return ReplayClientEventsAddLimit(builder, limit)
def ReplayClientEventsEnd(builder): return builder.EndObject()
def End(builder):
    return ReplayClientEventsEnd(builder)