# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class StorageMaintenanceInProgress(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StorageMaintenanceInProgress()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStorageMaintenanceInProgress(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # StorageMaintenanceInProgress
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def StorageMaintenanceInProgressStart(builder): builder.StartObject(0)
def Start(builder):
    return StorageMaintenanceInProgressStart(builder)
def StorageMaintenanceInProgressEnd(builder): return builder.EndObject()
def End(builder):
    return StorageMaintenanceInProgressEnd(builder)