# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WorldStateActionEntry(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WorldStateActionEntry()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWorldStateActionEntry(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # WorldStateActionEntry
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WorldStateActionEntry
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # WorldStateActionEntry
    def ActionType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # WorldStateActionEntry
    def Action(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def WorldStateActionEntryStart(builder): builder.StartObject(3)
def Start(builder):
    return WorldStateActionEntryStart(builder)
def WorldStateActionEntryAddId(builder, id): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)
def AddId(builder, id):
    return WorldStateActionEntryAddId(builder, id)
def WorldStateActionEntryAddActionType(builder, actionType): builder.PrependUint8Slot(1, actionType, 0)
def AddActionType(builder, actionType):
    return WorldStateActionEntryAddActionType(builder, actionType)
def WorldStateActionEntryAddAction(builder, action): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(action), 0)
def AddAction(builder, action):
    return WorldStateActionEntryAddAction(builder, action)
def WorldStateActionEntryEnd(builder): return builder.EndObject()
def End(builder):
    return WorldStateActionEntryEnd(builder)