# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

class WorldStateActionUnion(object):
    NONE = 0
    WsRequestProperty = 1
    WsRequestProperties = 2
    WsRequestSystemProperty = 3
    WsRequestVerbs = 4
    WsRequestVerbCode = 5
    WsResolveObject = 6
    WsListObjects = 7
    WsRequestAllObjects = 8
    WsUpdateProperty = 9
    WsProgramVerb = 10
    WsGetObjectFlags = 11
    WsQueryObjects = 12
