# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WorldStateResultEntry(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WorldStateResultEntry()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWorldStateResultEntry(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # WorldStateResultEntry
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WorldStateResultEntry
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # WorldStateResultEntry
    def ResultType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # WorldStateResultEntry
    def Result(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def WorldStateResultEntryStart(builder): builder.StartObject(3)
def Start(builder):
    return WorldStateResultEntryStart(builder)
def WorldStateResultEntryAddId(builder, id): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)
def AddId(builder, id):
    return WorldStateResultEntryAddId(builder, id)
def WorldStateResultEntryAddResultType(builder, resultType): builder.PrependUint8Slot(1, resultType, 0)
def AddResultType(builder, resultType):
    return WorldStateResultEntryAddResultType(builder, resultType)
def WorldStateResultEntryAddResult(builder, result): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(result), 0)
def AddResult(builder, result):
    return WorldStateResultEntryAddResult(builder, result)
def WorldStateResultEntryEnd(builder): return builder.EndObject()
def End(builder):
    return WorldStateResultEntryEnd(builder)