# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

class WorldStateResultUnion(object):
    NONE = 0
    WsPropertyResult = 1
    WsPropertiesResult = 2
    WsSystemPropertyResult = 3
    WsVerbsResult = 4
    WsVerbCodeResult = 5
    WsResolveResult = 6
    WsObjectsListResult = 7
    WsAllObjectsResult = 8
    WsPropertyUpdatedResult = 9
    WsVerbProgrammedResult = 10
    WsObjectFlagsResult = 11
    WsQueryObjectsResult = 12
    WsActionError = 13
