# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WsObjectFlagsResult(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WsObjectFlagsResult()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWsObjectFlagsResult(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # WsObjectFlagsResult
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WsObjectFlagsResult
    def Flags(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

def WsObjectFlagsResultStart(builder): builder.StartObject(1)
def Start(builder):
    return WsObjectFlagsResultStart(builder)
def WsObjectFlagsResultAddFlags(builder, flags): builder.PrependUint16Slot(0, flags, 0)
def AddFlags(builder, flags):
    return WsObjectFlagsResultAddFlags(builder, flags)
def WsObjectFlagsResultEnd(builder): return builder.EndObject()
def End(builder):
    return WsObjectFlagsResultEnd(builder)