# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WsObjectsListResult(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WsObjectsListResult()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWsObjectsListResult(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # WsObjectsListResult
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WsObjectsListResult
    def Objects(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from MoorRpc.ObjectInfo import ObjectInfo
            obj = ObjectInfo()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # WsObjectsListResult
    def ObjectsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # WsObjectsListResult
    def ObjectsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def WsObjectsListResultStart(builder): builder.StartObject(1)
def Start(builder):
    return WsObjectsListResultStart(builder)
def WsObjectsListResultAddObjects(builder, objects): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(objects), 0)
def AddObjects(builder, objects):
    return WsObjectsListResultAddObjects(builder, objects)
def WsObjectsListResultStartObjectsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartObjectsVector(builder, numElems):
    return WsObjectsListResultStartObjectsVector(builder, numElems)
def WsObjectsListResultEnd(builder): return builder.EndObject()
def End(builder):
    return WsObjectsListResultEnd(builder)