# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WsProgramVerb(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WsProgramVerb()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWsProgramVerb(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # WsProgramVerb
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WsProgramVerb
    def Object(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.ObjectRef import ObjectRef
            obj = ObjectRef()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # WsProgramVerb
    def VerbName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.Symbol import Symbol
            obj = Symbol()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # WsProgramVerb
    def Code(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # WsProgramVerb
    def CodeLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # WsProgramVerb
    def CodeIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def WsProgramVerbStart(builder): builder.StartObject(3)
def Start(builder):
    return WsProgramVerbStart(builder)
def WsProgramVerbAddObject(builder, object): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(object), 0)
def AddObject(builder, object):
    return WsProgramVerbAddObject(builder, object)
def WsProgramVerbAddVerbName(builder, verbName): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(verbName), 0)
def AddVerbName(builder, verbName):
    return WsProgramVerbAddVerbName(builder, verbName)
def WsProgramVerbAddCode(builder, code): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(code), 0)
def AddCode(builder, code):
    return WsProgramVerbAddCode(builder, code)
def WsProgramVerbStartCodeVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartCodeVector(builder, numElems):
    return WsProgramVerbStartCodeVector(builder, numElems)
def WsProgramVerbEnd(builder): return builder.EndObject()
def End(builder):
    return WsProgramVerbEnd(builder)