# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WsPropertiesResult(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WsPropertiesResult()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWsPropertiesResult(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # WsPropertiesResult
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WsPropertiesResult
    def Properties(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from MoorCommon.PropInfo import PropInfo
            obj = PropInfo()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # WsPropertiesResult
    def PropertiesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # WsPropertiesResult
    def PropertiesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def WsPropertiesResultStart(builder): builder.StartObject(1)
def Start(builder):
    return WsPropertiesResultStart(builder)
def WsPropertiesResultAddProperties(builder, properties): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(properties), 0)
def AddProperties(builder, properties):
    return WsPropertiesResultAddProperties(builder, properties)
def WsPropertiesResultStartPropertiesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartPropertiesVector(builder, numElems):
    return WsPropertiesResultStartPropertiesVector(builder, numElems)
def WsPropertiesResultEnd(builder): return builder.EndObject()
def End(builder):
    return WsPropertiesResultEnd(builder)