# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WsQueryObjectsResult(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WsQueryObjectsResult()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWsQueryObjectsResult(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # WsQueryObjectsResult
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WsQueryObjectsResult
    def Objects(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from MoorCommon.Obj import Obj
            obj = Obj()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # WsQueryObjectsResult
    def ObjectsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # WsQueryObjectsResult
    def ObjectsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def WsQueryObjectsResultStart(builder): builder.StartObject(1)
def Start(builder):
    return WsQueryObjectsResultStart(builder)
def WsQueryObjectsResultAddObjects(builder, objects): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(objects), 0)
def AddObjects(builder, objects):
    return WsQueryObjectsResultAddObjects(builder, objects)
def WsQueryObjectsResultStartObjectsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartObjectsVector(builder, numElems):
    return WsQueryObjectsResultStartObjectsVector(builder, numElems)
def WsQueryObjectsResultEnd(builder): return builder.EndObject()
def End(builder):
    return WsQueryObjectsResultEnd(builder)