# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WsQueryObjects(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WsQueryObjects()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWsQueryObjects(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # WsQueryObjects
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WsQueryObjects
    def Parent(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.Obj import Obj
            obj = Obj()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # WsQueryObjects
    def Location(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.Obj import Obj
            obj = Obj()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # WsQueryObjects
    def Owner(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.Obj import Obj
            obj = Obj()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # WsQueryObjects
    def FlagsAll(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # WsQueryObjects
    def FlagsAny(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

def WsQueryObjectsStart(builder): builder.StartObject(5)
def Start(builder):
    return WsQueryObjectsStart(builder)
def WsQueryObjectsAddParent(builder, parent): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(parent), 0)
def AddParent(builder, parent):
    return WsQueryObjectsAddParent(builder, parent)
def WsQueryObjectsAddLocation(builder, location): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(location), 0)
def AddLocation(builder, location):
    return WsQueryObjectsAddLocation(builder, location)
def WsQueryObjectsAddOwner(builder, owner): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(owner), 0)
def AddOwner(builder, owner):
    return WsQueryObjectsAddOwner(builder, owner)
def WsQueryObjectsAddFlagsAll(builder, flagsAll): builder.PrependUint16Slot(3, flagsAll, 0)
def AddFlagsAll(builder, flagsAll):
    return WsQueryObjectsAddFlagsAll(builder, flagsAll)
def WsQueryObjectsAddFlagsAny(builder, flagsAny): builder.PrependUint16Slot(4, flagsAny, 0)
def AddFlagsAny(builder, flagsAny):
    return WsQueryObjectsAddFlagsAny(builder, flagsAny)
def WsQueryObjectsEnd(builder): return builder.EndObject()
def End(builder):
    return WsQueryObjectsEnd(builder)