# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WsRequestProperties(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WsRequestProperties()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWsRequestProperties(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # WsRequestProperties
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WsRequestProperties
    def Object(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.ObjectRef import ObjectRef
            obj = ObjectRef()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # WsRequestProperties
    def Inherited(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def WsRequestPropertiesStart(builder): builder.StartObject(2)
def Start(builder):
    return WsRequestPropertiesStart(builder)
def WsRequestPropertiesAddObject(builder, object): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(object), 0)
def AddObject(builder, object):
    return WsRequestPropertiesAddObject(builder, object)
def WsRequestPropertiesAddInherited(builder, inherited): builder.PrependBoolSlot(1, inherited, 0)
def AddInherited(builder, inherited):
    return WsRequestPropertiesAddInherited(builder, inherited)
def WsRequestPropertiesEnd(builder): return builder.EndObject()
def End(builder):
    return WsRequestPropertiesEnd(builder)