# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WsRequestProperty(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WsRequestProperty()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWsRequestProperty(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # WsRequestProperty
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WsRequestProperty
    def Object(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.ObjectRef import ObjectRef
            obj = ObjectRef()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # WsRequestProperty
    def Property(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.Symbol import Symbol
            obj = Symbol()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def WsRequestPropertyStart(builder): builder.StartObject(2)
def Start(builder):
    return WsRequestPropertyStart(builder)
def WsRequestPropertyAddObject(builder, object): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(object), 0)
def AddObject(builder, object):
    return WsRequestPropertyAddObject(builder, object)
def WsRequestPropertyAddProperty(builder, property): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(property), 0)
def AddProperty(builder, property):
    return WsRequestPropertyAddProperty(builder, property)
def WsRequestPropertyEnd(builder): return builder.EndObject()
def End(builder):
    return WsRequestPropertyEnd(builder)