# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WsResolveObject(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WsResolveObject()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWsResolveObject(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # WsResolveObject
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WsResolveObject
    def Objref(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.ObjectRef import ObjectRef
            obj = ObjectRef()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def WsResolveObjectStart(builder): builder.StartObject(1)
def Start(builder):
    return WsResolveObjectStart(builder)
def WsResolveObjectAddObjref(builder, objref): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(objref), 0)
def AddObjref(builder, objref):
    return WsResolveObjectAddObjref(builder, objref)
def WsResolveObjectEnd(builder): return builder.EndObject()
def End(builder):
    return WsResolveObjectEnd(builder)