# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WsRequestVerbs(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WsRequestVerbs()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWsRequestVerbs(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # WsRequestVerbs
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WsRequestVerbs
    def Object(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.ObjectRef import ObjectRef
            obj = ObjectRef()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # WsRequestVerbs
    def Inherited(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def WsRequestVerbsStart(builder): builder.StartObject(2)
def Start(builder):
    return WsRequestVerbsStart(builder)
def WsRequestVerbsAddObject(builder, object): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(object), 0)
def AddObject(builder, object):
    return WsRequestVerbsAddObject(builder, object)
def WsRequestVerbsAddInherited(builder, inherited): builder.PrependBoolSlot(1, inherited, 0)
def AddInherited(builder, inherited):
    return WsRequestVerbsAddInherited(builder, inherited)
def WsRequestVerbsEnd(builder): return builder.EndObject()
def End(builder):
    return WsRequestVerbsEnd(builder)