# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WsRequestAllObjects(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WsRequestAllObjects()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWsRequestAllObjects(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # WsRequestAllObjects
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def WsRequestAllObjectsStart(builder): builder.StartObject(0)
def Start(builder):
    return WsRequestAllObjectsStart(builder)
def WsRequestAllObjectsEnd(builder): return builder.EndObject()
def End(builder):
    return WsRequestAllObjectsEnd(builder)