# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WsRequestVerbCode(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WsRequestVerbCode()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWsRequestVerbCode(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # WsRequestVerbCode
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WsRequestVerbCode
    def Object(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.ObjectRef import ObjectRef
            obj = ObjectRef()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # WsRequestVerbCode
    def Verb(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.Symbol import Symbol
            obj = Symbol()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def WsRequestVerbCodeStart(builder): builder.StartObject(2)
def Start(builder):
    return WsRequestVerbCodeStart(builder)
def WsRequestVerbCodeAddObject(builder, object): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(object), 0)
def AddObject(builder, object):
    return WsRequestVerbCodeAddObject(builder, object)
def WsRequestVerbCodeAddVerb(builder, verb): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(verb), 0)
def AddVerb(builder, verb):
    return WsRequestVerbCodeAddVerb(builder, verb)
def WsRequestVerbCodeEnd(builder): return builder.EndObject()
def End(builder):
    return WsRequestVerbCodeEnd(builder)