# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WsRequestSystemProperty(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WsRequestSystemProperty()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWsRequestSystemProperty(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # WsRequestSystemProperty
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WsRequestSystemProperty
    def Object(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.ObjectRef import ObjectRef
            obj = ObjectRef()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # WsRequestSystemProperty
    def Property(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.Symbol import Symbol
            obj = Symbol()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def WsRequestSystemPropertyStart(builder): builder.StartObject(2)
def Start(builder):
    return WsRequestSystemPropertyStart(builder)
def WsRequestSystemPropertyAddObject(builder, object): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(object), 0)
def AddObject(builder, object):
    return WsRequestSystemPropertyAddObject(builder, object)
def WsRequestSystemPropertyAddProperty(builder, property): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(property), 0)
def AddProperty(builder, property):
    return WsRequestSystemPropertyAddProperty(builder, property)
def WsRequestSystemPropertyEnd(builder): return builder.EndObject()
def End(builder):
    return WsRequestSystemPropertyEnd(builder)