# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WsUpdateProperty(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WsUpdateProperty()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWsUpdateProperty(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # WsUpdateProperty
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WsUpdateProperty
    def Object(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.ObjectRef import ObjectRef
            obj = ObjectRef()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # WsUpdateProperty
    def Property(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.Symbol import Symbol
            obj = Symbol()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # WsUpdateProperty
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorVar.Var import Var
            obj = Var()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def WsUpdatePropertyStart(builder): builder.StartObject(3)
def Start(builder):
    return WsUpdatePropertyStart(builder)
def WsUpdatePropertyAddObject(builder, object): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(object), 0)
def AddObject(builder, object):
    return WsUpdatePropertyAddObject(builder, object)
def WsUpdatePropertyAddProperty(builder, property): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(property), 0)
def AddProperty(builder, property):
    return WsUpdatePropertyAddProperty(builder, property)
def WsUpdatePropertyAddValue(builder, value): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(value), 0)
def AddValue(builder, value):
    return WsUpdatePropertyAddValue(builder, value)
def WsUpdatePropertyEnd(builder): return builder.EndObject()
def End(builder):
    return WsUpdatePropertyEnd(builder)