# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WsVerbsResult(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WsVerbsResult()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWsVerbsResult(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # WsVerbsResult
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WsVerbsResult
    def Verbs(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from MoorCommon.VerbInfo import VerbInfo
            obj = VerbInfo()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # WsVerbsResult
    def VerbsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # WsVerbsResult
    def VerbsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def WsVerbsResultStart(builder): builder.StartObject(1)
def Start(builder):
    return WsVerbsResultStart(builder)
def WsVerbsResultAddVerbs(builder, verbs): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(verbs), 0)
def AddVerbs(builder, verbs):
    return WsVerbsResultAddVerbs(builder, verbs)
def WsVerbsResultStartVerbsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartVerbsVector(builder, numElems):
    return WsVerbsResultStartVerbsVector(builder, numElems)
def WsVerbsResultEnd(builder): return builder.EndObject()
def End(builder):
    return WsVerbsResultEnd(builder)